const QUIZ_META = {
  id: 'lom-oks-kalkyl',
  title: 'Driftsregnskap og kalkyler',
  subtitle: 'Økonomistyring – Kap. 9 og 11',
  description: '30 spørsmål om driftsregnskap, selvkostmetoden, bidragsmetoden, kalkylasjon i handelsbedrifter og avviksanalyse.',
  cats: {
    driftsregnskap: { label: 'Driftsregnskap', color: '#8b5cf6' },
    selvkost:       { label: 'Selvkostmetoden', color: '#3b82f6' },
    bidrag:         { label: 'Bidragsmetoden', color: '#10b981' },
    avviksanalyse:  { label: 'Kalkylasjon og avviksanalyse', color: '#f59e0b' },
  }
};

const QUESTIONS = [
  {
    cat: 'driftsregnskap',
    catLabel: 'Driftsregnskap',
    q: 'Hva er formålet med driftsregnskapet?',
    opts: [
      'Å gi intern styringsinformasjon om lønnsomheten per produkt, prosjekt eller avdeling – grunnlag for priskalkylering',
      'Å oppfylle regnskapslovens krav om perioderapportering til myndigheter, revisorer og offentlige tilsynsorgan hvert kvartal',
      'Å utarbeide årsrapporten med balanse, resultatregnskap og noter til aksjonærene',
      'Å beregne skattemessige avskrivninger og skattbart overskudd per år',
    ],
    correct: 0,
    explain: 'Driftsregnskapet er et internt, frivillig styringsverktøy. Det viser lønnsomheten per produkt, prosjekt, avdeling eller kunde – og er grunnlaget for priskalkylering og ledelsesbeslutninger.',
  },
  {
    cat: 'driftsregnskap',
    catLabel: 'Driftsregnskap',
    q: 'Hvilke typer driftsregnskap finnes?',
    opts: [
      'Resultatregnskap, balanseregnskap og kontantstrømoppstilling – de tre obligatoriske delene av årsregnskapet',
      'Avdelingsregnskap, prosjektregnskap og produktregnskap',
      'Finansregnskap, skatteregnskap og likviditetsregnskap – tre lovpålagte rapporter',
      'Budsjett, rullerende prognose og perioderapport – verktøy for fremtidsplanlegging',
    ],
    correct: 1,
    explain: 'Driftsregnskapet finnes i flere former: avdelingsregnskap (per avdeling), prosjektregnskap (per oppdrag) og produktregnskap (per produkt). Alle gir mer detaljert informasjon enn finansregnskapet.',
  },
  {
    cat: 'driftsregnskap',
    catLabel: 'Driftsregnskap',
    q: 'Hva er koblingen mellom driftsregnskapet og kalkylene?',
    opts: [
      'Kalkyler og driftsregnskap utarbeides uavhengig av hverandre – to separate styringssystemer uten innbyrdes påvirkning',
      'Driftsregnskapet fra ferdige prosjekter gir tilleggssatser som brukes til å kalkulere priser for fremtidige prosjekter',
      'Kalkylene kan erstatte driftsregnskapet dersom bedriften har svært god priskontroll og stabile kost-inntektsforhold over tid',
      'Driftsregnskapet brukes bare til å etterprøve budsjetter – ikke til å beregne tilleggssatser',
    ],
    correct: 1,
    explain: 'Flytdiagrammet viser sammenhengen: Ferdige prosjekter → Driftsregnskap → Beregning av tilleggssatser (%) → Kalkyler → Kalkulere pris for kommende prosjekter. Historisk data driver fremtidige kalkyler.',
  },
  {
    cat: 'selvkost',
    catLabel: 'Selvkostmetoden',
    q: 'Hva er selvkostmetoden?',
    opts: [
      'En metode som fordeler variable kostnader per enhet – faste kostnader belastes samlet på periodens resultat',
      'En metode som tar med ALLE kostnader (direkte og indirekte, faste og variable) i produktets kalkyle',
      'En metode som tar med tilvirkningskost pluss salgskostnader, men utelater administrasjonskostnader',
      'En metode for å fastsette minimumsavkastning på investert kapital per produkt',
    ],
    correct: 1,
    explain: 'Selvkostmetoden inkluderer alle kostnader i produktkalkylen: direkte materialkostnader + direkte lønnskostnader + indirekte produksjonskostnader + indirekte salgs- og administrasjonskostnader = selvkost.',
  },
  {
    cat: 'selvkost',
    catLabel: 'Selvkostmetoden',
    q: 'Hva er oppbygningen av selvkostprisen?',
    opts: [
      'Direkte materialkostnad + Direkte lønnskostnad = Tilvirkningskost; + Indirekte S&A-kostnader = Selvkost; + Fortjeneste = Salgsinntekt',
      'Variable kostnader per enhet + Andel faste kostnader per enhet = Selvkost; Selvkost + Dekningsbidrag beregnet som prosentpåslag = Salgspris fastsatt av markedet',
      'Innkjøpspris + Fraktkostnad + Toll = Varekostnad; + Tillegg for administrasjon = Salgspris',
      'Direkte lønn + Indirekte produksjonskostnader = Selvkost; + Avanse = Utsalgspris',
    ],
    correct: 0,
    explain: 'Selvkostmetoden: Direkte materialkostnad + Direkte lønnskostnad + Andre direkte kostnader = Tilvirkningskost. Tilvirkningskost + Indirekte salgs- og administrasjonskostnader = Selvkost. Selvkost + Fortjeneste = Salgsinntekt.',
  },
  {
    cat: 'selvkost',
    catLabel: 'Selvkostmetoden',
    q: 'Hva er differensierte tillegg i selvkostkalkylen?',
    opts: [
      'Et samlet prosenttillegg på tilvirkningskost som dekker alle indirekte kostnader under ett',
      'Ulike tilleggssatser for ulike kategorier av indirekte kostnader: materialtillegg, driftstillegg, administrasjonstillegg og salgstillegg',
      'Tillegg som justeres fortløpende basert på faktiske kostnader i produksjonen og korrigeres månedlig',
      'Rabatter og pristillegg som varierer med ordrevolum og kundekategori',
    ],
    correct: 1,
    explain: 'Differensierte tillegg betyr at indirekte kostnader fordeles med ulike satser for ulike kostnadskategorier: materialtillegg (% av materialkostnad), driftstillegg (% av direkte lønn), administrasjonstillegg og salgstillegg.',
  },
  {
    cat: 'selvkost',
    catLabel: 'Selvkostmetoden',
    q: 'Hva er en potensiell ulempe med selvkostmetoden?',
    opts: [
      'Den er for tidkrevende å beregne og krever spesialisert regnskapsprogramvare med avanserte fordelingsnøkler',
      '"Urettferdige tillegg" der produkter med høy direkte lønn belastes mye indirekte kost – kan føre til avvisning av lønnsomme tilleggsordrer',
      'Den ignorerer faste kostnader og undervurderer dermed produktenes reelle kostnad',
      'Den gir for lav salgspris fordi avansen beregnes av varekostnad og ikke av salgspris',
    ],
    correct: 1,
    explain: 'Selvkostmetodens svakhet er at fordelingen av indirekte kostnader kan slå uheldig ut: produkter med høy direkte lønnskostnad får uforholdsmessig høy andel av felleskostnader, og kan feilaktig virke ulønnsomme.',
  },
  {
    cat: 'selvkost',
    catLabel: 'Selvkostmetoden',
    q: 'Hva er tillegg for indirekte kostnader per faktureringstime?',
    opts: [
      'Andel indirekte kostnader / Antall fakturerte timer – gir en timesats for indirekte kostnader',
      'Totale indirekte kostnader / Totale arbeidstimer (inkl. ikke-fakturerte) – gir gjennomsnittlig belastning per arbeidstime uavhengig av faktureringsstatus',
      'Direkte lønnskostnad per time × Tilleggssatsen for driftstillegg i prosent',
      'Indirekte kostnader / Antall utstedte fakturaer – gir kostnad per faktura',
    ],
    correct: 0,
    explain: 'Tillegg per faktureringstime = Total andel indirekte kostnader / Antall fakturerte timer. Dette gir en timesats som legges til direkte timer i kalkylene for å dekke indirekte kostnader.',
  },
  {
    cat: 'bidrag',
    catLabel: 'Bidragsmetoden',
    q: 'Hva er bidragsmetoden?',
    opts: [
      'En metode som fordeler alle kostnader – faste og variable – jevnt på samtlige produkter',
      'En metode for å beregne offentlige tilskudd og støtteordninger per produkt',
      'En metode som kun inkluderer de produksjonsavhengige (variable) kostnadene i produktkalkylen – faste kostnader holdes utenfor',
      'En metode som tar med tilvirkningskost og salgskostnader, men utelater administrasjonsomkostninger',
    ],
    correct: 2,
    explain: 'Bidragsmetoden inkluderer kun de variable kostnadene i produktkalkylen. Faste kostnader behandles som periodekostnader. Salgspris − Variable kostnader = Dekningsbidrag (DB).',
  },
  {
    cat: 'bidrag',
    catLabel: 'Bidragsmetoden',
    q: 'Hva er dekningsbidrag (DB)?',
    opts: [
      'Salgspris minus selvkost – viser nettogevinsten per enhet etter at alle variable, faste og indirekte kostnader er fullt ut dekket',
      'Driftsresultat fratrukket finanskostnader og skatt – bedriftens årsresultat',
      'Salgspris minus variable kostnader = bidraget til dekning av faste kostnader og fortjeneste',
      'Bruttofortjeneste fratrukket avskrivninger og kapitalkostnader i perioden',
    ],
    correct: 2,
    explain: 'DB = Salgspris − Variable kostnader. Dekningsbidraget viser hva produktet bidrar med til å dekke faste kostnader og fortjeneste. Summen av DB fra alle produkter minus samlede faste kostnader = resultat.',
  },
  {
    cat: 'bidrag',
    catLabel: 'Bidragsmetoden',
    q: 'Hva er dekningsgrad (DG)?',
    opts: [
      'DG = Dekningsbidrag / Salgsinntekter × 100 – viser DB som andel av salgsprisen',
      'DG = Faste kostnader / Salgsinntekter × 100 – viser hvor stor del av omsetningen som går til faste kostnader',
      'DG = Variable kostnader / Salgsinntekter × 100 – viser kostnadsprosenten per salgskrone',
      'DG = Driftsresultat / Salgsinntekter × 100 – viser overskuddet som andel av omsetningen',
    ],
    correct: 0,
    explain: 'DG = Dekningsbidrag / Salgsinntekter × 100. Viser hvor stor andel av salgsprisen som er igjen etter at variable kostnader er dekket. Høy DG er bra – mer bidrag per salgskrone.',
  },
  {
    cat: 'bidrag',
    catLabel: 'Bidragsmetoden',
    q: 'Hva er forutsetningene for at bidragsmetoden er gyldig?',
    opts: [
      'At faste kostnader er kjente og stabile, og at produktmiksen holdes uendret gjennom hele planleggingsperioden uten sesongvariasjoner',
      'At bedriften opererer i et marked med fast pris og standardiserte vilkår – uten rabatter, volumavtaler eller individuelle kundeavtaler',
      'Proporsjonale variable kostnader, stabile faste kostnader og fast salgspris innenfor det relevante kapasitetsintervallet',
      'At dekningsgraden er positiv og at bedriften har ledig produksjonskapasitet',
    ],
    correct: 2,
    explain: 'Bidragsmetoden forutsetter: (1) proporsjonale variable kostnader (konstant DB per enhet), (2) stabile faste kostnader innenfor kapasitetsintervallet, og (3) fast pris uavhengig av mengde.',
  },
  {
    cat: 'bidrag',
    catLabel: 'Bidragsmetoden',
    q: 'Når anbefales bidragsmetoden fremfor selvkostmetoden?',
    opts: [
      'Ved langsiktig prissetting – bidragsmetoden sikrer at alle variable og faste kostnader dekkes over hele planleggingshorisonten',
      'Når bedriften vil unngå kompliserte fordelingsnøkler for indirekte kostnader',
      'I tjenesteytende virksomheter – selvkostmetoden er forbeholdt vareproduksjon',
      'I spesialtilfeller: lavsesong med ledig kapasitet, tilleggsordrer og midlertidige prisforhandlinger – men ikke for langsiktig prissetting',
    ],
    correct: 3,
    explain: 'Selvkostmetoden anbefales for langsiktig prissetting (alle kostnader må dekkes). Bidragsmetoden brukes kortsiktig ved ledig kapasitet, tilleggsordrer, lavsesong eller etterspørselssvikt – da er det lønnsomt å ta ordrer som gir positivt DB.',
  },
  {
    cat: 'bidrag',
    catLabel: 'Bidragsmetoden',
    q: 'Hva er salgsmerkost (minimumskostnad) i bidragsmetoden?',
    opts: [
      'Den laveste prisen et produkt kan selges for og gi positivt bidrag – dvs. de variable kostnadene for ordren',
      'Selvkostprisen justert ned med et rimelig fortjenestebeløp for rabatterte kunder',
      'Summen av direkte materialkostnader og direkte lønnskostnader for produktet',
      'Den prisen som gir null i dekningsbidrag – beregnet som selvkost minus administrasjonstillegg og salgstillegg',
    ],
    correct: 0,
    explain: 'Salgsmerkost (minimumspris/differansepris) = de variable kostnadene som direkte påløper for ordren. Alt over denne prisen gir positivt dekningsbidrag og kan aksepteres når det er ledig kapasitet.',
  },
  {
    cat: 'avviksanalyse',
    catLabel: 'Kalkylasjon og avviksanalyse',
    q: 'Hva er bruttofortjeneste i varehandel, og hva er avanse?',
    opts: [
      'Bruttofortjeneste = Salgsinntekter − Varekostnad (i kr); Avanse = Bruttofortjeneste / Varekostnad × 100',
      'Bruttofortjeneste = Salgsinntekter − Alle driftskostnader; Avanse = Bruttofortjeneste / Salgsinntekter × 100',
      'Bruttofortjeneste = Varekostnad × Avanseprosent / 100; Avanse = Salgspris − Driftskostnad',
      'Bruttofortjeneste = Dekningsbidrag fratrukket faste kostnader; Avanse = Bruttofortjeneste / Driftskostnad × 100',
    ],
    correct: 0,
    explain: 'I varehandel: BF = Salgsinntekter − Varekostnad (i kr). BFP = BF / Salgsinntekter × 100 (av salgsprisen). Avanse = BF / Varekostnad × 100 (av innkjøpsprisen). Avansen er alltid høyere enn BFP.',
  },
  {
    cat: 'avviksanalyse',
    catLabel: 'Kalkylasjon og avviksanalyse',
    q: 'Hva er forkalkyler og etterkalkyler?',
    opts: [
      'Forkalkyler er grove overslag; etterkalkyler er mer detaljerte beregninger av samme prosjekt',
      'Forkalkyler oppdateres løpende underveis i prosjektet og justeres ved endringer; etterkalkyler er budsjettets endelige og godkjente versjon',
      'Forkalkyler brukes internt for styring; etterkalkyler rapporteres til kunder og myndigheter',
      'Forkalkyler beregnes FØR jobben/prosjektet (prisgrunnlag); etterkalkyler beregnes ETTER (faktiske kostnader – grunnlag for avviksanalyse)',
    ],
    correct: 3,
    explain: 'Forkalkyler utarbeides FØR jobben starter og brukes som grunnlag for prissetting. Etterkalkyler beregnes ETTER jobben er ferdig basert på faktiske kostnader – og sammenlignes med forkalkylen for avviksanalyse.',
  },
  {
    cat: 'avviksanalyse',
    catLabel: 'Kalkylasjon og avviksanalyse',
    q: 'Hva er mengdeavvik i avviksanalyse?',
    opts: [
      '(Faktisk forbrukt mengde − Planlagt mengde) × Planlagt pris – viser effektivitetsavvik',
      '(Faktisk pris − Planlagt pris) × Faktisk forbrukt mengde – viser prisavvikets samlede kostnadspåvirkning på periodens budsjett og endelige resultat',
      '(Planlagt mengde − Faktisk mengde) × Faktisk pris – viser avvik vurdert til virkelige priser',
      '(Faktisk salgsmengde − Budsjettert salgsmengde) × Planlagt dekningsbidrag per enhet',
    ],
    correct: 0,
    explain: 'Mengdeavvik = (Faktisk forbrukt mengde − Planlagt mengde) × Planlagt pris. Viser om man brukte mer eller mindre materialer/tid enn planlagt. Positivt avvik = brukte mer enn planlagt (negativt for resultat).',
  },
  {
    cat: 'avviksanalyse',
    catLabel: 'Kalkylasjon og avviksanalyse',
    q: 'Hva er prisavvik i avviksanalyse?',
    opts: [
      '(Faktisk forbrukt mengde − Planlagt mengde) × Planlagt pris – viser forbruksavvikets kostnadspåvirkning',
      '(Planlagt pris − Faktisk pris) × Planlagt mengde – viser prisendringens effekt på budsjettert forbruk',
      '(Virkelig pris − Planlagt pris) × Faktisk mengde – viser om man betalte mer eller mindre enn planlagt',
      '(Faktisk salgspris − Budsjettert salgspris) × Faktisk salgsvolum – viser inntektsavvik fra prisjustering',
    ],
    correct: 2,
    explain: 'Prisavvik = (Virkelig pris − Planlagt pris) × Faktisk forbrukt mengde. Viser om prisene på innsatsfaktorer (materialer, arbeidstimer) ble som planlagt. Positivt avvik = betalte mer enn planlagt.',
  },
  {
    cat: 'avviksanalyse',
    catLabel: 'Kalkylasjon og avviksanalyse',
    q: 'Hva brukes avviksanalyse til?',
    opts: [
      'Å beregne nye tilleggssatser og påslagsprosenter for kommende kalkyleår basert på gjennomsnitt av siste tre regnskapsperioder',
      'Å dokumentere avvikshendelser for revisor og sikre etterlevelse av internkontroll- og rapporteringskrav',
      'Å vurdere om prosjektlederen har overholdt budsjettet – grunnlag for personalevaluering',
      'Å identifisere årsaker til avvik mellom planlagte og faktiske kostnader – grunnlag for tiltak, prissetting og budsjettforbedring',
    ],
    correct: 3,
    explain: 'Avviksanalyse gir innsikt i HOW og HVORFOR det oppsto avvik mellom planlagt og faktisk. Dette gir grunnlag for: tiltak, korreksjon av fremtidige kalkyler og forbedring av budsjettering.',
  },
  {
    cat: 'driftsregnskap',
    catLabel: 'Driftsregnskap',
    q: 'Hva er forskjellen mellom direkte og indirekte kostnader i driftsregnskapet?',
    opts: [
      'Direkte kostnader kan knyttes direkte til et produkt/prosjekt; indirekte kostnader kan ikke det og fordeles med fordelingsnøkkel',
      'Direkte kostnader er variable og proporsjonate; indirekte kostnader er alltid faste, periodeuavhengige og belastes resultatet samlet',
      'Direkte kostnader betales kontant og umiddelbart; indirekte kostnader faktureres i etterkant',
      'Direkte kostnader inngår i tilvirkningskost; indirekte kostnader utelates fra produktkalkylen',
    ],
    correct: 0,
    explain: 'Direkte kostnader er sporbare til ett bestemt produkt eller prosjekt (f.eks. råvarer til produkt A). Indirekte kostnader (overhead) kan ikke direkte tilordnes og fordeles på produkter via en fordelingsnøkkel.',
  },
  {
    cat: 'selvkost',
    catLabel: 'Selvkostmetoden',
    q: 'Hva er tilvirkningskost?',
    opts: [
      'Summen av variable kostnader per enhet inkl. andel faste produksjonskostnader – grunnlag for DB-beregning',
      'Kun råvare- og materialkostnader som direkte kan knyttes til det ferdige produktet',
      'Summen av direkte produksjonskostnader (materialer + lønn + andre direkte) + indirekte produksjonskostnader',
      'Selvkost minus salgs- og administrasjonskostnader – den rene fremstillingskostnaden fratrukket alle overhead-poster',
    ],
    correct: 2,
    explain: 'Tilvirkningskost = Direkte materialkostnader + Direkte lønnskostnader + Andre direkte kostnader + Indirekte produksjonskostnader. Dette er kostnadene knyttet til selve produksjonen – ekskludert salgs- og administrasjonskostnader.',
  },
  {
    cat: 'bidrag',
    catLabel: 'Bidragsmetoden',
    q: 'Hva er "salgsmerkost = minimumskostnad" i praktisk sammenheng?',
    opts: [
      'Selvkostprisen fratrukket et minimumskrav til fortjeneste – brukes ved anbud og prisforhandlinger',
      'Gjennomsnittlig tilvirkningskost per enhet beregnet over siste tolv måneder',
      'De variable kostnadene per enhet pluss en forholdsmessig andel av faste kostnader og administrasjonsomkostninger',
      'Den prisen man minimum kan ta for å ikke tape penger på én enkelt ordre ved ledig kapasitet – dvs. kun variable kostnader for den konkrete ordren',
    ],
    correct: 3,
    explain: 'Salgsmerkost (minimumspris) ved ledig kapasitet = de variable kostnadene for den spesifikke ordren. Alt over denne prisen gir positivt DB og bidrar til å dekke faste kostnader. Gjelder kun på kort sikt og ved ledig kapasitet.',
  },
  {
    cat: 'avviksanalyse',
    catLabel: 'Kalkylasjon og avviksanalyse',
    q: 'En snekker beregner at et skap skal koste 2 000 kr i materialer, men faktisk forbruk er 2 400 kr. Hva er avviket og hva kan årsaken være?',
    opts: [
      'Negativt mengdeavvik og/eller prisavvik på kr 400 – mer forbruk, høyere innkjøpspris, eller svinn',
      'Positivt prisavvik på kr 400 – materialprisen steg og ga høyere inntekter enn budsjettert',
      'Negativt salgsprisavvik på kr 400 – snekkeren satte for lav pris og dekker ikke materialene til prosjektet',
      'Null avvik totalt – kr 400 er innenfor det kalkulerte sikkerhetsmarginalet på ±25%',
    ],
    correct: 0,
    explain: 'Avviktet på kr 400 kan skyldes mengdeavvik (brukte mer materiale enn planlagt p.g.a. feil eller svinn) og/eller prisavvik (innkjøpsprisene var høyere). Avviksanalysen er grunnlaget for å finne årsaken.',
  },
  {
    cat: 'selvkost',
    catLabel: 'Selvkostmetoden',
    q: 'Hva er påslag for materialer i kalkylasjon?',
    opts: [
      'Innkjøpsprisen multiplisert med en fast faktor fastsatt av bransjenormen for å komme frem til kalkylepris',
      'Fraktkostnader og emballasjekostnader fordelt som et fast beløp per materialenhet',
      'Andel indirekte kostnader / Direkte materialkostnader × 100 – et prosenttillegg på materialkostnader for å dekke indirekte materialkostnader',
      'Differansen mellom markedspris og innkjøpspris – viser marginen på videresolgte materialer',
    ],
    correct: 2,
    explain: 'Påslag for materialer = Andel indirekte materialkostnader / Direkte materialkostnader × 100. Dette prosenttillegget legges på direkte materialkostnader i kalkylen for å fordele indirekte lagerkostnader, innkjøpskostnader osv.',
  },
  {
    cat: 'avviksanalyse',
    catLabel: 'Kalkylasjon og avviksanalyse',
    q: 'Hva er for- og etterkalkylers verdi for budsjettprosessen?',
    opts: [
      'Forkalkyler brukes til skatterapportering; etterkalkyler inngår i årsregnskapet som revisor kontrollerer',
      'Forkalkyler er grunnlaget for finansiering og låneavtaler; etterkalkyler dokumenterer at midlene er brukt riktig',
      'Forkalkyler og etterkalkyler sikrer at prosjekter er tilstrekkelig lønnsomme til å tilfredsstille kravet om minimumsavkastning',
      'Etterkalkyler gir faktiske kostnadstall som forbedrer grunnlaget for neste periodes forkalkyler og budsjetter',
    ],
    correct: 3,
    explain: 'Etterkalkyler gir faktiske kostnadsdata som systematisk forbedrer neste periodes forkalkyler og budsjetter. Avviksanalysen identifiserer hva som gikk annerledes og gir kunnskap som gjør fremtidige kalkyler mer presise.',
  },
  {
    cat: 'bidrag',
    catLabel: 'Bidragsmetoden',
    q: 'En bedrift selger produkt A for kr 500 og har variable kostnader på kr 300. Hva er dekningsbidraget og dekningsgraden?',
    opts: [
      'DB = kr 200; DG = 40%',
      'DB = kr 300; DG = 60%',
      'DB = kr 200; DG = 60%',
      'DB = kr 500; DG = 100%',
    ],
    correct: 0,
    explain: 'DB = Salgspris − Variable kostnader = 500 − 300 = kr 200. DG = DB / Salgspris × 100 = 200/500 × 100 = 40%. 40 øre av hver krone i salg bidrar til å dekke faste kostnader og fortjeneste.',
  },
  {
    cat: 'driftsregnskap',
    catLabel: 'Driftsregnskap',
    q: 'Hva er et prosjektregnskap?',
    opts: [
      'En samlet oversikt over alle aktive og planlagte investeringsprosjekter med budsjett og fremdriftsstatus',
      'Et fremtidsrettet budsjett som viser forventet inntjening på et planlagt prosjekt',
      'Et driftsregnskap som viser alle inntekter og kostnader knyttet til ett bestemt oppdrag eller prosjekt',
      'En periodisk rapport over prosjektporteføljen – brukes i kvartalsrapportering til styret',
    ],
    correct: 2,
    explain: 'Et prosjektregnskap er et driftsregnskap for ett spesifikt prosjekt eller oppdrag. Det viser alle direkte og indirekte kostnader belastet prosjektet, samt inntekter – og gir et bilde av prosjektets lønnsomhet.',
  },
  {
    cat: 'selvkost',
    catLabel: 'Selvkostmetoden',
    q: 'Hva er anbefalingen for langsiktig prissetting – selvkost eller bidragsmetode?',
    opts: [
      'Bidragsmetoden – den sikrer positivt dekningsbidrag og er tilstrekkelig for lønnsom drift over tid',
      'Begge metoder er like velegnet – valget beror på bedriftens produktmiks og kostnadstruktur',
      'Bidragsmetoden kombinert med selvkost – variabelkostnader dekkes kortsiktig, faste kostnader langsiktig',
      'Selvkostmetoden – på lang sikt må ALLE kostnader dekkes for at bedriften skal overleve',
    ],
    correct: 3,
    explain: 'Selvkostmetoden anbefales for langsiktig prissetting fordi alle kostnader (faste og variable) må dekkes over tid for at bedriften skal overleve. Bidragsmetoden er et kortsiktig hjelpemiddel ved spesielle situasjoner.',
  },
  {
    type: 'sort',
    cat: 'selvkost',
    catLabel: 'Selvkostmetoden',
    q: 'Sorter hvert kostnadselement etter hvilke(n) kalkylemetode(r) som tar det med i produktkalkylen.',
    bins: [
      { id: 'begge',  label: 'Inngår i begge metoder',  color: '#10b981' },
      { id: 'kun_sk', label: 'Kun i selvkostkalkylen',  color: '#8b5cf6' },
    ],
    items: [
      { text: 'Direkte materialkostnader per enhet',             bin: 'begge' },
      { text: 'Direkte lønnskostnader per enhet',                bin: 'begge' },
      { text: 'Indirekte administrasjonskostnader (tillegg)',     bin: 'kun_sk' },
      { text: 'Indirekte salgskostnader (tillegg)',               bin: 'kun_sk' },
      { text: 'Proporsjonale variable produksjonskostnader',      bin: 'begge' },
      { text: 'Andel faste produksjonsomkostninger (tillegg)',    bin: 'kun_sk' },
    ],
    explain: 'Bidragsmetoden tar kun med variable kostnader (direkte materialer, lønn og proporsjonale variable). Selvkostmetoden tar med ALLE kostnader inkludert indirekte og faste via tilleggssatser.',
  },
  {
    cat: 'bidrag',
    catLabel: 'Bidragsmetoden',
    q: 'I hvilke to situasjoner anbefales bidragsmetoden fremfor selvkostmetoden?',
    opts: [
      'Langsiktig prissetting der alle kostnader skal dekkes inn over tid',
      'Lavsesong der bedriften har ledig produksjonskapasitet som ellers er ubrukt',
      'Vurdering av en tilleggsordre som kan aksepteres til lavere enn normal pris',
      'Beregning av normalpriser som skal dekke alle faste og variable kostnader',
    ],
    correct: [1, 2],
    explain: 'Bidragsmetoden brukes kortsiktig ved ledig kapasitet (lavsesong) og ved tilleggsordrer – da er det lønnsomt å ta ordrer som gir positivt dekningsbidrag selv om de ikke dekker alle kostnader. Selvkostmetoden brukes til langsiktig normalprissetting.',
  },
];
