const QUIZ_META = {
  id: 'lom-oks-tillegg',
  title: 'Økonomi: Tillegg',
  subtitle: 'LØM Fagskole · Supplement',
  description: '25 spørsmål om MVA, selskapsformer, regnskapslover og kontantstrømsanalyse.',
  cats: {
    mva_avgift:     { label: 'MVA og avgifter', color: '#8b5cf6' },
    selskapsformer: { label: 'Selskapsformer', color: '#3b82f6' },
    regnskapslover: { label: 'Regnskapsregler', color: '#10b981' },
    kontantstrom:   { label: 'Kontantstrøm', color: '#f59e0b' },
  }
};

const QUESTIONS = [
  {
    cat: 'mva_avgift',
    catLabel: 'MVA og avgifter',
    q: 'Hva er den generelle merverdiavgiftssatsen (MVA) i Norge?',
    opts: [
      '12 %',
      '15 %',
      '20 %',
      '25 %',
    ],
    correct: 3,
    explain: 'Den generelle MVA-satsen i Norge er 25 %. Den gjelder de fleste varer og tjenester som ikke faller inn under de reduserte satsene.',
  },
  {
    cat: 'mva_avgift',
    catLabel: 'MVA og avgifter',
    q: 'Hvilken MVA-sats gjelder for matvarer?',
    opts: [
      '12 %',
      '15 %',
      '25 %',
      '0 %',
    ],
    correct: 1,
    explain: 'Matvarer har redusert MVA-sats på 15 % i Norge. Dette gjelder næringsmidler, men ikke f.eks. restaurantmåltider (25 %).',
  },
  {
    cat: 'mva_avgift',
    catLabel: 'MVA og avgifter',
    q: 'Hvilken MVA-sats gjelder for persontransport, overnatting (hotell) og kino?',
    opts: [
      '6 %',
      '12 %',
      '15 %',
      '25 %',
    ],
    correct: 1,
    explain: 'Persontransport (buss, tog, fly), overnattingstjenester (hotell) og kino har redusert MVA-sats på 12 % i Norge.',
  },
  {
    cat: 'mva_avgift',
    catLabel: 'MVA og avgifter',
    q: 'Hva er omsetningsgrensen for MVA-registrering i Norge?',
    opts: [
      '20 000 kr',
      '50 000 kr',
      '100 000 kr',
      '150 000 kr',
    ],
    correct: 1,
    explain: 'Virksomheter med omsetning over 50 000 kr i løpet av en 12-månedersperiode er pliktige til å registrere seg i MVA-registeret og kreve inn og innberette MVA.',
  },
  {
    cat: 'mva_avgift',
    catLabel: 'MVA og avgifter',
    q: 'Hva er arbeidsgiveravgiften (AGA) i sone 1 (sentrale strøk)?',
    opts: [
      '10,6 %',
      '12,5 %',
      '14,1 %',
      '16,8 %',
    ],
    correct: 2,
    explain: 'AGA i sone 1 er 14,1 % av brutto lønn. Arbeidsgiveravgiften betales av arbeidsgiver til staten i tillegg til den ansattes lønn og er ikke synlig for arbeidstaker.',
  },
  {
    cat: 'mva_avgift',
    catLabel: 'MVA og avgifter',
    q: 'Hva er inngående MVA?',
    opts: [
      'MVA du beregner og legger på fakturaen din til kunder ved salg av avgiftspliktige varer',
      'MVA du betaler til leverandørene på kjøp av varer og tjenester til bruk i virksomheten',
      'MVA som refunderes automatisk fra staten når varer eksporteres til land utenfor EØS',
      'MVA-andelen som innberettes og overføres til Skatteetaten ved periodens slutt',
    ],
    correct: 1,
    explain: 'Inngående MVA er den MVA du betaler på innkjøp til virksomheten. Du kan trekke denne fra utgående MVA (den du krever inn fra kundene), og betaler kun differansen til staten.',
  },
  {
    cat: 'mva_avgift',
    catLabel: 'MVA og avgifter',
    q: 'Hva er utgående MVA?',
    opts: [
      'MVA du betaler til leverandørene på innkjøp av varer og tjenester til virksomheten',
      'MVA du beregner og krever inn fra kundene ved salg av avgiftspliktige varer og tjenester',
      'MVA-refusjonen du søker om og mottar tilbake fra Skatteetaten når inngående MVA overstiger utgående i en gitt termin',
      'MVA som gjelder ved eksport av varer og tjenester til kunder utenfor Norges grenser',
    ],
    correct: 1,
    explain: 'Utgående MVA er den MVA du krever inn fra kundene ved salg. Netto MVA til staten = Utgående MVA − Inngående MVA (fradragsberettiget inngående MVA).',
  },
  {
    cat: 'selskapsformer',
    catLabel: 'Selskapsformer',
    q: 'Hva er den viktigste egenskapen ved et enkeltpersonforetak (ENK) mht. ansvar?',
    opts: [
      'Begrenset ansvar – eieren risikerer kun den kapitalen som er skutt inn i foretaket',
      'Ubegrenset personlig ansvar – eieren er personlig ansvarlig for all gjeld og forpliktelser',
      'Solidarisk ansvar mellom eier og eventuelle familiemedlemmer som er registrert som deltakere',
      'Ansvar begrenset til foretakets egne eiendeler, driftsmidler og bankinnskudd',
    ],
    correct: 1,
    explain: 'ENK: eieren har ubegrenset personlig ansvar. All gjeld i foretaket er også eierens private gjeld – kreditorene kan gå på eierens private formue.',
  },
  {
    cat: 'selskapsformer',
    catLabel: 'Selskapsformer',
    q: 'Hva er minstekravet til aksjekapital ved stiftelse av et AS?',
    opts: [
      '30 000 kr',
      '10 000 kr',
      '50 000 kr',
      '100 000 kr',
    ],
    correct: 0,
    explain: 'Aksjeloven krever at et AS stiftes med minimum 30 000 kr i aksjekapital. Aksjeeierne har begrenset ansvar og risikerer maksimalt den innskutte aksjekapitalen.',
  },
  {
    cat: 'selskapsformer',
    catLabel: 'Selskapsformer',
    q: 'Hva skiller et ANS fra et AS mht. deltakernes ansvar?',
    opts: [
      'ANS gir deltakerne begrenset ansvar på lik linje med aksjonærer i et AS, slik at privat formue er beskyttet',
      'ANS-deltakerne har ansvar begrenset til innskutt kapital og avtalte andeler',
      'I et ANS er deltakerne solidarisk og ubegrenset ansvarlige for selskapets gjeld',
      'ANS krever særskilt tillatelse fra myndighetene og er underlagt konsesjonsplikt',
    ],
    correct: 2,
    explain: 'ANS (Ansvarlig selskap): deltakerne er solidarisk og ubegrenset ansvarlig for selskapets forpliktelser. En kreditor kan kreve hele gjelden fra én enkelt deltaker.',
  },
  {
    cat: 'selskapsformer',
    catLabel: 'Selskapsformer',
    q: 'Hvordan beskattes overskuddet i et enkeltpersonforetak (ENK)?',
    opts: [
      'Med selskapsskatt på flat 22 %, på samme måte som for et AS',
      'ENK-overskudd er skattefritt de første 3 driftsårene etter stiftelse i henhold til oppstartsreglene',
      'Med utbytteskatt på rundt 37,84 %, tilsvarende AS-utbytte etter aksjonærmodellen',
      'Som personinntekt hos eieren, inkludert trinnskatt og trygdeavgift',
    ],
    correct: 3,
    explain: 'Overskuddet i ENK beskattes som personinntekt – eieren betaler trinnskatt og trygdeavgift. Dette kan gi vesentlig høyere skatt enn i et AS ved høy inntekt.',
  },
  {
    cat: 'selskapsformer',
    catLabel: 'Selskapsformer',
    q: 'Hva er en fusjon?',
    opts: [
      'Sammenslåing av to eller flere selskaper til ett felles selskap',
      'Oppdeling av ett selskap i to eller flere selvstendige, separate selskaper med egne styrer og eierstrukturer',
      'Overdragelse av enkeltaktiva eller forretningsenheter mellom to selskaper',
      'Avvikling og formell nedleggelse av et selskaps samlede virksomhet',
    ],
    correct: 0,
    explain: 'Fusjon = to eller flere selskaper slås sammen til ett. Fisjon = ett selskap deles opp i to eller flere. Fusjon kan gi stordriftsfordeler, synergieffekter og økt markedsandel.',
  },
  {
    cat: 'selskapsformer',
    catLabel: 'Selskapsformer',
    q: 'Hva er en fisjon?',
    opts: [
      'Sammenslåing av to eller flere selskaper til ett nytt felles selskap med felles styre og ledelse',
      'Salg av nye aksjer til eksterne investorer for å hente inn egenkapital',
      'Deling av ett selskap i to eller flere separate selskaper',
      'Frivillig avvikling og avslutning av et selskaps virksomhet',
    ],
    correct: 2,
    explain: 'Fisjon betyr at ett selskap deles opp i to eller flere separate selskaper. Brukes f.eks. for å skille ut en virksomhetsgren som et eget selskap med egne eiere.',
  },
  {
    cat: 'selskapsformer',
    catLabel: 'Selskapsformer',
    q: 'Hva er den viktigste fordelen med AS fremfor ENK?',
    opts: [
      'AS gir alltid lavere skatt enn ENK, uavhengig av inntektsnivå og uttak fra selskapet',
      'AS er fritatt for krav til regnskap, revisjon og rapportering til Brønnøysundregistrene for mindre selskaper',
      'Begrenset ansvar – eierne risikerer kun innskutt aksjekapital, ikke privat formue',
      'AS er vesentlig enklere og raskere å avvikle og oppløse enn ENK',
    ],
    correct: 2,
    explain: 'Aksjonærer i et AS har begrenset ansvar og risikerer maksimalt det de har skutt inn i selskapet. Privat formue er beskyttet mot selskapets kreditorer – dette er AS-formens fremste fordel.',
  },
  {
    cat: 'regnskapslover',
    catLabel: 'Regnskapsregler',
    q: 'Hvem er regnskapspliktige etter Regnskapsloven?',
    opts: [
      'Kun aksjeselskaper (AS) og allmennaksjeselskaper (ASA) med mer enn 10 ansatte og omsetning over 5 mill. kr',
      'Kun børsnoterte selskaper som er underlagt løpende tilsyn fra Finanstilsynet og IFRS-krav',
      'Alle registrerte virksomheter, uavhengig av størrelse, form og omsetning',
      'AS, ASA, ANS/DA med inntekt over terskel, ENK med omsetning over 5 mill. kr og andre foretak bestemt ved lov',
    ],
    correct: 3,
    explain: 'Regnskapspliktige etter Regnskapsloven er bl.a. alle AS og ASA, ANS/DA med inntekt over terskel, og ENK med omsetning over 5 mill. kr. Små foretak har forenklede krav.',
  },
  {
    cat: 'regnskapslover',
    catLabel: 'Regnskapsregler',
    q: 'Hva er oppbevaringsplikten for regnskapsdokumentasjon etter Bokføringsloven?',
    opts: [
      '3,5 år',
      '5 år',
      '7 år',
      '10 år',
    ],
    correct: 3,
    explain: 'Bokføringsloven: primær dokumentasjon (bilag) skal oppbevares i minimum 5 år, men avtaler, korrespondanse og annen sekundær dokumentasjon skal oppbevares i minimum 10 år.',
  },
  {
    cat: 'regnskapslover',
    catLabel: 'Regnskapsregler',
    q: 'Hva er Bokføringsloven sitt formål?',
    opts: [
      'Å stille krav til hvordan transaksjoner registreres, dokumenteres og oppbevares for å sikre sporbarhet',
      'Å fastsette hvilke skattesatser og avgiftsregler som gjelder for norske virksomheter i henhold til skatteloven',
      'Å regulere utbytteutdeling fra AS og stille krav til innholdet i aksjonæravtaler',
      'Å fastsette krav til revisjon, revisors arbeidsmetodikk og revisors uavhengighet',
    ],
    correct: 0,
    explain: 'Bokføringsloven stiller krav til løpende bokføring, dokumentasjon (bilag) og oppbevaring av regnskapsopplysninger. Formålet er å sikre at regnskapet er etterprøvbart og kontrollerbart.',
  },
  {
    cat: 'regnskapslover',
    catLabel: 'Regnskapsregler',
    q: 'Hva er forskjellen mellom finansregnskapet og driftsregnskapet?',
    opts: [
      'Finansregnskapet er primært til intern styring; driftsregnskapet leveres til Brønnøysundregistrene',
      'De to begrepene er i praksis synonyme og brukes om hverandre i norsk regnskapslitteratur',
      'Finansregnskapet viser virksomhetens totale økonomi for omverdenen; driftsregnskapet gir interne kalkyler per produkt/avdeling for ledelsesbeslutninger',
      'Driftsregnskapet er lovpålagt og leveres til Skatteetaten; finansregnskapet er et frivillig tilleggsregnskap',
    ],
    correct: 2,
    explain: 'Finansregnskap (eksternt): årsregnskap, balanse og resultat for aksjonærer, kreditorer og myndigheter. Driftsregnskap (internt): kalkyler og bidragsanalyser per produkt/avdeling – beslutningsstøtte for ledelsen.',
  },
  {
    cat: 'regnskapslover',
    catLabel: 'Regnskapsregler',
    q: 'Hva er tidsavgrensningsprinsippet (matching principle) i regnskapet?',
    opts: [
      'At regnskapsåret alltid utgjør nøyaktig 12 hele måneder fra januar til desember',
      'At avskrivninger beregnes og fordeles likt over hele eiendelens forventede levetid',
      'At innberetning og betaling av MVA-terminer skjer hvert kvartal til Skatteetaten',
      'At inntekter og kostnader føres i den perioden de er opptjent/påløpt, uavhengig av når kontantbetalingen skjer',
    ],
    correct: 3,
    explain: 'Tidsavgrensningsprinsippet: inntekter og kostnader henføres til den regnskapsperioden de tilhører, uavhengig av kontantstrømmen. Eksempel: forhåndsbetalte abonnementer periodiseres over den aktuelle perioden.',
  },
  {
    cat: 'kontantstrom',
    catLabel: 'Kontantstrøm',
    q: 'Hva er endring i arbeidskapital, og hva skjer med den i starten av et investeringsprosjekt?',
    opts: [
      'Endring i arbeidskapital = økning i omløpsmidler minus økning i kortsiktig gjeld; ved prosjektstart binder mer lager og kunder kapital – negativ kontantstrøm',
      'Økning i arbeidskapital regnes som en positiv kontantstrøm fordi den synliggjør prosjektets vekst og styrker totalfinansieringen i henhold til standard investeringsteori',
      'Arbeidskapital holdes normalt utenfor investeringsanalysen fordi den antas å være uendret gjennom hele prosjektperioden og dermed ikke påvirker nåverdiberegningen',
      'Endring i arbeidskapital = økning i anleggsmidler og langsiktige, bundne investeringer i driftsutstyr',
    ],
    correct: 0,
    explain: 'Økt arbeidskapitalbehov ved prosjektstart (mer lager, mer kundekreditt) binder opp likviditet – negativ kontantstrøm i starten. Mot slutten frigjøres arbeidskapitalen og gir positiv kontantstrøm.',
  },
  {
    cat: 'kontantstrom',
    catLabel: 'Kontantstrøm',
    q: 'Hva er restverdi (terminal value) og når inntreffer den i en kontantstrømanalyse?',
    opts: [
      'Den opprinnelige anskaffelseskostnaden for investeringen – bokføres som utbetaling i år 0 og inngår i nåverdiberegningen som negativ kontantstrøm',
      'De løpende og periodiske vedlikeholdskostnadene som påløper gjennom hele investeringens levetid og reduserer driftskontantstrømmene hvert år',
      'Markedsverdien av investeringsobjektet og/eller frigjort arbeidskapital ved prosjektets slutt – positiv kontantstrøm i siste år',
      'Skattebesparelsen fra skattemessige avskrivninger – en jevn, positiv kontantstrøm hvert enkelt driftsår',
    ],
    correct: 2,
    explain: 'Restverdi = antatt salgsverdi av investeringsobjektet og frigjort arbeidskapital ved prosjektslutt. Disse er POSITIVE kontantstrømmer i det siste analyseåret og øker prosjektets lønnsomhet.',
  },
  {
    cat: 'kontantstrom',
    catLabel: 'Kontantstrøm',
    q: 'Hvorfor inkluderes IKKE avskrivninger som en kontantstrøm i investeringsanalysen?',
    opts: [
      'Fordi avskrivningsmetoden er vanskelig å fastslå nøyaktig over hele prosjektperioden',
      'Fordi avskrivninger inngår i driftsresultatet, men er inkludert separat under finansposter',
      'Fordi nyinvesteringer alltid avskrives lineært og dermed gir null netto kontanteffekt',
      'Fordi avskrivninger er en regnskapsmessig kostnad uten kontanteffekt – selve investeringen er allerede tatt som utbetaling i år 0',
    ],
    correct: 3,
    explain: 'Kontantstrømsanalysen inkluderer kun faktiske inn- og utbetalinger. Avskrivninger er en regnskapsmessig fordeling av investeringskostnaden – ingen ny kontantutbetaling – og skal ikke dobbeltføres.',
  },
  {
    cat: 'kontantstrom',
    catLabel: 'Kontantstrøm',
    q: 'Hva er sunk cost (irreversibel kostnad) og hvordan behandles det i investeringsanalyse?',
    opts: [
      'En allerede påløpt kostnad som ikke kan gjenvinnes; skal IKKE inkluderes siden den ikke påvirkes av fremtidige beslutninger',
      'En fremtidig kostnad som kan unngås ved valg av alternativt prosjekt; skal alltid tas med i analysen fordi den er beslutningsrelevant',
      'En skjult indirekte kostnad i produksjonen som ofte undervurderes i budsjetteringsfasen og fører til systematisk underkalkulering',
      'Finansieringskostnader og renter knyttet til lånet som finansierer den aktuelle investeringen',
    ],
    correct: 0,
    explain: 'Sunk cost = allerede brukte penger som ikke kan gjenvinnes uansett hvilken beslutning man tar fremover. Irreversible kostnader er ikke relevante for fremtidige beslutninger og holdes utenfor investeringsanalysen.',
  },
  {
    cat: 'kontantstrom',
    catLabel: 'Kontantstrøm',
    q: 'Hva er avkastningskravet i en investeringsanalyse?',
    opts: [
      'Den gjennomsnittlige rentesatsen på virksomhetens banklån og kredittfasiliteter',
      'Den forventede, garanterte avkastningen på norske statsobligasjoner til enhver tid',
      'Selskapsskatten på 22 % som er lovbestemt for alle norske AS og ASA',
      'Den minimumsavkastning investoren krever, bestående av risikofri rente, risikopremie og evt. inflasjon',
    ],
    correct: 3,
    explain: 'Avkastningskravet = risikofri rente + risikopremie + evt. inflasjon. Det uttrykker minimumsavkastningen investoren krever for å kompensere for kapitalbinding og den prosjektspesifikke risikoen.',
  },
  {
    cat: 'kontantstrom',
    catLabel: 'Kontantstrøm',
    q: 'Hva er formelen for tilbakebetalingstid (TBT) og hva er metodens viktigste svakhet?',
    opts: [
      'TBT = Investering / Gjennomsnittlig årlig netto kontantstrøm; svakhet: ignorerer tidsverdien av penger og kontantstrømmer etter TBT',
      'TBT = Investering / (Driftsinntekter − Driftskostnader + Avskrivninger); svakhet: avskrivninger bør holdes utenfor kontantstrømsberegningen og inkludering gir feil svar',
      'TBT = Netto nåverdi / Avkastningskrav; svakhet: avkastningskravet er vanskelig å anslå med tilstrekkelig presisjon og varierer med prosjektrisiko',
      'TBT = Investering × Avkastningskrav; svakhet: metoden justerer ikke for ulik investeringsstørrelse på tvers av prosjekter',
    ],
    correct: 0,
    explain: 'TBT = Investering / Gjennomsnittlig netto kontantstrøm per år. Svakhetene: (1) ignorerer tidsverdien av penger, (2) ser bort fra alle kontantstrømmer etter tilbakebetalingstidspunktet.',
  },
  {
    type: 'order',
    cat: 'mva_avgift',
    catLabel: 'MVA og avgifter',
    q: 'Sett MVA-satsene i riktig rekkefølge. Laveste sats øverst, høyeste sats nederst.',
    items: [
      '25 % – generell sats for de fleste varer og tjenester',
      '15 % – redusert sats for matvarer og næringsmidler',
      '12 % – redusert sats for persontransport, overnatting og kino',
      '0 % – eksport av varer og tjenester til utlandet',
    ],
    explain: 'MVA-satsene i Norge fra lavest til høyest: 0% (eksport), 12% (transport/hotell/kino), 15% (matvarer), 25% (generell sats). Husk at restaurantbesøk er 25%, mens mat kjøpt i butikk er 15%.',
  },
  {
    type: 'sort',
    cat: 'selskapsformer',
    catLabel: 'Selskapsformer',
    q: 'Sorter selskapsformene etter deltakernes ansvar for selskapets gjeld.',
    bins: [
      { id: 'begrenset',   label: 'Begrenset ansvar',             color: '#10b981' },
      { id: 'ubegrenset',  label: 'Ubegrenset / solidarisk ansvar', color: '#ef4444' },
    ],
    items: [
      { text: 'AS (Aksjeselskap)',              bin: 'begrenset' },
      { text: 'ASA (Allmennaksjeselskap)',      bin: 'begrenset' },
      { text: 'ENK (Enkeltpersonforetak)',      bin: 'ubegrenset' },
      { text: 'ANS (Ansvarlig selskap)',        bin: 'ubegrenset' },
    ],
    explain: 'Begrenset ansvar: AS og ASA – eierne risikerer kun innskutt kapital. Ubegrenset: ENK (eieren hefter personlig for all gjeld), ANS (deltakerne er solidarisk og ubegrenset ansvarlige).',
  },
  {
    cat: 'selskapsformer',
    catLabel: 'Selskapsformer',
    q: 'Hva er to kjennetegn ved et enkeltpersonforetak (ENK)?',
    opts: [
      'Eieren er personlig og ubegrenset ansvarlig for all gjeld i foretaket',
      'Foretaket er pliktig til å ha styre og daglig leder registrert i Brønnøysund',
      'Overskuddet beskattes som personinntekt med trinnskatt og trygdeavgift',
      'Stiftelse krever minimum 30 000 kr i aksjekapital i henhold til aksjeloven',
    ],
    correct: [0, 2],
    explain: 'ENK kjennetegnes av (1) ubegrenset personlig ansvar – eieren hefter med hele sin private formue, og (2) beskatning som personinntekt – overskuddet legges til eierens øvrige inntekt og beskattes med trinnskatt og trygdeavgift.',
  },
];
