const QUIZ_META = {
  id: 'lom-ool-endring',
  title: 'Endringsledelse og organisasjonsutvikling',
  subtitle: 'Organisasjon og ledelse – Kap. 7',
  description: '32 spørsmål om endringsledelse, Kotters 8 trinn, Lewins faser, interessentanalyse, OU, TKL, LEAN og den lærende organisasjon.',
  cats: {
    endring_def:   { label: 'Endringsledelse – grunnlag', color: '#8b5cf6' },
    modeller:      { label: 'Kotters og Lewins modeller', color: '#3b82f6' },
    interessenter: { label: 'Interessenter og motstand', color: '#ef4444' },
    ou_tql:        { label: 'OU, TKL, LEAN og Senge', color: '#10b981' },
  }
};

const QUESTIONS = [
  {
    cat: 'endring_def',
    catLabel: 'Endringsledelse – grunnlag',
    q: 'Hva er endringsledelse ifølge Wesenberg (2023)?',
    opts: [
      'En planmessig og målrettet prosess for å lede mennesker og organisasjoner gjennom ønskede endringer',
      'En styringsmodell for budsjettering og ressursfordeling i omstillingsperioder',
      'Et rammeverk for å revidere organisasjonsstrukturen og rapporteringslinjene',
      'En metode for å vurdere behovet for teknologi, kompetanse og systemoppgraderinger',
    ],
    correct: 0,
    explain: 'Endringsledelse er en planmessig og målrettet prosess for å lede mennesker og organisasjoner gjennom ønskede endringer, slik at endringene faktisk fester seg og gir ønskede resultater.',
  },
  {
    cat: 'endring_def',
    catLabel: 'Endringsledelse – grunnlag',
    q: 'Hvor stor andel av endringsforsøk mislykkes ifølge forskning på feltet?',
    opts: [
      '30 %',
      '50 %',
      '70 %',
      '90 %',
    ],
    correct: 2,
    explain: 'Forskning viser at om lag 70 % av alle endringsinitiativ i organisasjoner mislykkes – ofte fordi man undervurderer menneskesiden og fokuserer for mye på tekniske løsninger.',
  },
  {
    cat: 'endring_def',
    catLabel: 'Endringsledelse – grunnlag',
    q: 'Hva er implementeringssuksess-formelen fra pensum?',
    opts: [
      'Suksess = Strategi × (Mål + Ressurser + Tidsplan)',
      'Suksess = Kvalitet × (Eierskap + Motivasjon + Kunnskap)',
      'Suksess = Ledelse × (Struktur + Prosess + Kultur)',
      'Suksess = Kompetanse × (Vilje + Kapasitet + Forankring)',
    ],
    correct: 1,
    explain: 'Implementeringssuksess = Kvalitet × (Eierskap + Motivasjon + Kunnskap). Formelen viser at god teknisk kvalitet ikke er nok – ansatte må eie endringen, være motiverte og forstå den.',
  },
  {
    cat: 'endring_def',
    catLabel: 'Endringsledelse – grunnlag',
    q: 'Hva er endringskaleidoskopet, og hvilke dimensjoner inngår?',
    opts: [
      'En analysemodell med 8 komponenter: makt, tid, omfang, bevaring, mangfold, kompetanse, kapasitet og forankring',
      'En strategimodell med 6 dimensjoner: visjon, mål, kommunikasjon, struktur, kultur og evaluering',
      'En beslutningsmodell med 5 faser inspirert av Lewins tine-endre-fryse-tilnærming',
      'En kartleggingsmodell med 4 kategorier basert på interessentenes makt og engasjement',
    ],
    correct: 0,
    explain: 'Endringskaleidoskopet er et analyseverktøy med 8 komponenter som hjelper ledere vurdere konteksten for endring: maktforhold, tid, omfang, bevaring, mangfold, kompetanse, kapasitet og forankring.',
  },
  {
    cat: 'endring_def',
    catLabel: 'Endringsledelse – grunnlag',
    q: 'Hva er akseptmodellen i endringsledelse?',
    opts: [
      'En modell for å kartlegge graden av aksept blant berørte grupper og avdelinger',
      'Fire trinn ansatte må gjennom: vite → kunne → ville → ha lov',
      'En tilnærming for å evaluere om endringens mål ble nådd innen fastsatt frist',
      'En prosess for å håndtere motstand – fra dialog til formell godkjenning',
    ],
    correct: 1,
    explain: 'Akseptmodellen beskriver fire trinn ansatte må gjennom for å ta til seg en endring: vite (kjenne endringen), kunne (ha kompetanse), ville (være motivert) og ha lov (ha myndighet).',
  },
  {
    cat: 'endring_def',
    catLabel: 'Endringsledelse – grunnlag',
    q: 'Hva er en kommunikasjonsplan i endringsarbeid?',
    opts: [
      'En systematisk plan for hvem som skal informeres om hva, når og hvordan under endringsprosessen',
      'Et opplegg for å presentere endringens resultater for styret og eiere etter gjennomføring',
      'Et dokument som beskriver nye roller, kanaler og rutiner i den reviderte organisasjonen',
      'En oversikt over hvilke budskap som skal ut eksternt – til kunder, leverandører og media',
    ],
    correct: 0,
    explain: 'En kommunikasjonsplan sikrer at riktig informasjon når riktige interessenter til riktig tid og via riktige kanaler – kritisk for å redusere usikkerhet og motstand mot endring.',
  },
  {
    cat: 'modeller',
    catLabel: 'Kotters og Lewins modeller',
    q: 'Hva er de tre fasene i Lewins endringsmodell?',
    opts: [
      'Planlegge → Gjennomføre → Evaluere',
      'Analysere → Implementere → Følge opp',
      'Tine → Endre → Fryse',
      'Mobilisere → Transformere → Forankre',
    ],
    correct: 2,
    explain: 'Lewins tre faser: Tine (unfreeze – løsne opp etablerte mønstre), Endre (move – gjennomføre endringen) og Fryse (refreeze – forankre den nye tilstanden som ny norm).',
  },
  {
    cat: 'modeller',
    catLabel: 'Kotters og Lewins modeller',
    q: 'Hva representerer "tine"-fasen i Lewins modell?',
    opts: [
      'Å gjennomføre den planlagte endringen steg for steg i organisasjonen',
      'Å forankre den nye atferden som ny standard etter at endringen er gjort',
      'Å skape motivasjon og erkjennelse av at endring er nødvendig – løsne opp status quo',
      'Å kartlegge resultater og justere kursen basert på tilbakemeldinger fra ansatte',
    ],
    correct: 2,
    explain: 'Tine-fasen handler om å destabilisere status quo og skape motivasjon for endring – folk må innse at det eksisterende ikke fungerer godt nok og at endring er nødvendig.',
  },
  {
    cat: 'modeller',
    catLabel: 'Kotters og Lewins modeller',
    q: 'Hva er første steg i Kotters 8-trinnsmodell for endring?',
    opts: [
      'Bygge en ledende koalisjon av støttespillere med innflytelse og troverdighet',
      'Skape en følelse av krise og hastverk (urgency)',
      'Kommunisere endringsvisjonen bredt og tydelig i organisasjonen',
      'Forankre endringene i organisasjonens kultur og daglige praksis',
    ],
    correct: 1,
    explain: 'Kotters første trinn er å skape en sterk følelse av nødvendighet og hastverk (urgency) – uten dette vil ikke folk prioritere endringen fremfor daglig drift.',
  },
  {
    cat: 'modeller',
    catLabel: 'Kotters og Lewins modeller',
    q: 'Hva er det siste trinnet i Kotters 8-trinnsmodell?',
    opts: [
      'Planlegge og feire kortsiktige seire for å holde motivasjonen oppe',
      'Kommunisere endringsvisjonen til alle berørte medarbeidere',
      'Forankre endringene i organisasjonens kultur',
      'Fjerne barrierer og strukturer som hemmer gjennomføringen',
    ],
    correct: 2,
    explain: 'Kotters siste (8.) trinn er å forankre endringene dypt i organisasjonens kultur – slik at de nye måtene å jobbe på blir den nye normalen og ikke glir tilbake til gammel praksis.',
  },
  {
    cat: 'modeller',
    catLabel: 'Kotters og Lewins modeller',
    q: 'Hva er en viktig forskjell mellom Kotters og Lewins endringsmodeller?',
    opts: [
      'Lewin er primært utviklet for offentlig sektor; Kotter for kommersielle virksomheter',
      'Kotter har 8 detaljerte trinn med fokus på lederatferd; Lewin har 3 overordnede faser',
      'Lewin vektlegger tekniske løsninger; Kotter vektlegger menneskelige og kulturelle faktorer',
      'Kotter passer best for raske transformasjoner; Lewin for gradvise og langsiktige endringer',
    ],
    correct: 1,
    explain: 'Kotter tilbyr en mer detaljert, lederorientert 8-trinnsmodell med fokus på spesifikke handlinger ledere bør ta. Lewin gir en enklere, mer overordnet 3-fasemodell.',
  },
  {
    cat: 'interessenter',
    catLabel: 'Interessenter og motstand',
    q: 'Hva er en interessentanalyse i endringsarbeid?',
    opts: [
      'En vurdering av hvilke avdelinger som vil berøres mest av endringen og trenger ekstra støtte',
      'En kartlegging av alle berørte parter etter to dimensjoner: makt og interesse – for å prioritere involvering',
      'En analyse av markedets reaksjon på organisatoriske endringer og omdømmerisiko',
      'Et verktøy for å kartlegge interne konflikter og avgjøre hvem som bør involveres i løsningen',
    ],
    correct: 1,
    explain: 'Interessentanalysen kartlegger alle som berøres av endringen og plasserer dem i en 2×2 matrise etter makt (høy/lav) og interesse (høy/lav) – for å avgjøre hvor mye innsats som bør legges i å involvere dem.',
  },
  {
    cat: 'interessenter',
    catLabel: 'Interessenter og motstand',
    q: 'Hvem bør prioriteres høyest i en interessentanalyse?',
    opts: [
      'De med lav makt og høy interesse',
      'De med høy makt og lav interesse',
      'De med høy makt og høy interesse',
      'De med lav makt og lav interesse',
    ],
    correct: 2,
    explain: 'Interessenter med høy makt og høy interesse er "nøkkelspillere" som bør involveres aktivt. De har både mulighet til å blokkere endringen og sterk motivasjon til å gjøre det.',
  },
  {
    cat: 'interessenter',
    catLabel: 'Interessenter og motstand',
    q: 'Hvilke er de vanligste årsakene til motstand mot endring ifølge Kanter (1992)?',
    opts: [
      'Tap av kontroll, høy usikkerhet, mangel på informasjon og frykt for å tape noe man har',
      'Manglende digital kompetanse og utfordringer med nye teknologiske systemer',
      'Uenighet om endringsstrategien og ønsket om andre prioriteringer',
      'Dårlig timing, for høyt endringstempo og utilstrekkelige ressurser',
    ],
    correct: 0,
    explain: 'Kanter identifiserte motstand mot endring som drevet av: tap av kontroll, usikkerhet om fremtiden, mangel på tilstrekkelig informasjon, frykt for å miste noe man verdsetter, og bekymring for inkompetanse.',
  },
  {
    cat: 'interessenter',
    catLabel: 'Interessenter og motstand',
    q: 'Hva er det beste virkemiddelet for å redusere motstand mot endring?',
    opts: [
      'Å gjennomføre endringen i rolig tempo, steg for steg, slik at ansatte rekker å tilpasse seg',
      'Å gi berørte medarbeidere ekstra tid og ressurser til å mestre den nye situasjonen',
      'Tidlig og ærlig kommunikasjon kombinert med reell involvering av berørte parter',
      'Å sikre at ledere er synlige og tilgjengelige gjennom hele gjennomføringsfasen',
    ],
    correct: 2,
    explain: 'Tidlig, ærlig og god kommunikasjon om hvorfor endringen skjer og hva den innebærer, kombinert med reell involvering av de berørte, er det mest effektive virkemiddelet mot motstand.',
  },
  {
    cat: 'ou_tql',
    catLabel: 'OU, TKL, LEAN og Senge',
    q: 'Hva er organisasjonsutvikling (OU) sin todelte definisjon?',
    opts: [
      'Å styrke lederkompetansen og forbedre samhandlingen mellom avdelinger',
      'Å forbedre interne prosesser og øke produktiviteten gjennom systematisk forbedringsarbeid',
      'Å modernisere strukturer og innføre ny teknologi tilpasset markedets behov',
      'Å tilpasse organisasjonen til omgivelsene OG tilfredsstille ansattes behov for vekst og utvikling',
    ],
    correct: 3,
    explain: 'OU har to dimensjoner: (1) tilpasse organisasjonen til skiftende omgivelser og (2) tilfredsstille ansattes behov for vekst, mestring og utvikling – begge er nødvendige for varig suksess.',
  },
  {
    cat: 'ou_tql',
    catLabel: 'OU, TKL, LEAN og Senge',
    q: 'Hva er Total Kvalitetsledelse (TKL/TQM)?',
    opts: [
      'En ledelsesfilosofi opprinnelig fra Japan med fokus på kontinuerlig forbedring, kundefokus og beste praksis i alle ledd',
      'Et styringssystem for å overvåke kostnader og avvik i produksjon og leverandørkjede',
      'En sertifiseringsordning for kvalitetssikring av produkter og tjenester i sluttleveransen',
      'En metode for å rangere og belønne ansatte etter individuelle bidrag til kvalitetsmål',
    ],
    correct: 0,
    explain: 'TKL (Total Quality Management) er en helhetlig ledelsesfilosofi opprinnelig fra Japan (Deming) med fokus på kontinuerlig forbedring, totalt kundefokus og involvering av alle ansatte i kvalitetsarbeidet.',
  },
  {
    cat: 'ou_tql',
    catLabel: 'OU, TKL, LEAN og Senge',
    q: 'Hva er PDCA-hjulet, og hvem er det knyttet til?',
    opts: [
      'En markedsføringssirkel (Product, Distribution, Communication, Audience) – Kotler',
      'En endringsledelsesmodell (Prioritize, Delegate, Control, Adjust) – Kotter',
      'En kvalitetsforbedringssirkel (Plan, Do, Check, Act) – Deming',
      'En budsjetteringssyklus (Plan, Distribute, Control, Assess) – Lewin',
    ],
    correct: 2,
    explain: 'PDCA-hjulet (Plan-Do-Check-Act), også kalt Deming-hjulet, er et verktøy for kontinuerlig forbedring: planlegg tiltak → gjennomfør → sjekk resultater → juster og forbedre.',
  },
  {
    cat: 'ou_tql',
    catLabel: 'OU, TKL, LEAN og Senge',
    q: 'Hva er LEAN, og hva er dets hovedmål?',
    opts: [
      'En finansmodell for å beregne avkastning og lønnsomhet ved investeringer i prosessforbedring',
      'En teknisk tilnærming for å forenkle produktdesign og redusere antall komponenter',
      'En personalmodell for å kartlegge og effektivisere bemanningsbehov på tvers av avdelinger',
      'En ledelsesfilosofi avledet fra TKL med fokus på å eliminere all sløsing (muda) i alle prosesser',
    ],
    correct: 3,
    explain: 'LEAN er en produksjons- og ledelsesfilosofi opprinnelig fra Toyota, avledet fra TKL, med fokus på å eliminere all sløsing (muda/waste) i prosesser og levere maksimal verdi til kunden.',
  },
  {
    cat: 'ou_tql',
    catLabel: 'OU, TKL, LEAN og Senge',
    q: 'Hva kjennetegner "den lærende organisasjon" slik Peter Senge beskriver det?',
    opts: [
      'En organisasjon som kontinuerlig utvikler kapasitet til å skape ønskede resultater gjennom 5 disipliner',
      'En organisasjon med strukturerte opplæringsprogrammer og obligatorisk faglig påfyll hvert år',
      'En organisasjon som systematisk evaluerer prosjekter og deler erfaringer på tvers av team',
      'En organisasjon der ledere tar ansvar for kunnskapsoverføring og faglig veiledning av ansatte',
    ],
    correct: 0,
    explain: 'Senges lærende organisasjon kontinuerlig utvikler og utvider sin kapasitet gjennom 5 disipliner: systemtenkning, personlig mestring, mentale modeller, felles visjon og læring i team.',
  },
  {
    cat: 'ou_tql',
    catLabel: 'OU, TKL, LEAN og Senge',
    q: 'Hva er "systemtenkning" som Senges 5. og overordnede disiplin?',
    opts: [
      'Å digitalisere informasjonsflyt og knytte avdelinger sammen gjennom felles IT-plattformer',
      'Å kartlegge organisasjonens delsystemer og tydeliggjøre ansvarsområder og grensesnitt',
      'Å se helheten og sammenhengene mellom deler i organisasjonen fremfor å se på isolerte hendelser',
      'Å bruke strukturerte analysemetoder for å planlegge og fordele ressurser på tvers av enheter',
    ],
    correct: 2,
    explain: 'Systemtenkning er evnen til å se organisasjonen som et komplekst system av sammenhenger og feedback-sløyfer – fremfor å fokusere på isolerte hendelser. Det er den overordnede disiplinen som binder de andre 4 sammen.',
  },
  {
    cat: 'ou_tql',
    catLabel: 'OU, TKL, LEAN og Senge',
    q: 'Hva er "personlig mestring" i Senges modell?',
    opts: [
      'At lederen tar ansvar for å forme kulturen og sette standarden for ønsket atferd',
      'At ledere bygger bred faglig kompetanse og kan fylle ulike roller i organisasjonen',
      'At ansatte jobber målrettet mot toppresultater og konkurrerer om de beste prestasjonene',
      'At hvert individ forplikter seg til livslang læring og kontinuerlig utvikling av egne ferdigheter og forståelse',
    ],
    correct: 3,
    explain: 'Personlig mestring handler om individets forpliktelse til livslang læring, kontinuerlig klargjøring av personlig visjon og å se virkeligheten objektivt. Organisasjoner lærer bare gjennom individer som lærer.',
  },
  {
    cat: 'ou_tql',
    catLabel: 'OU, TKL, LEAN og Senge',
    q: 'Hva er "felles visjon" i Senges modell?',
    opts: [
      'En ekte, delt visjon som engasjerer og forplikter alle i organisasjonen – ikke bare pålagt ovenfra',
      'En strategiplan som ledergruppen utvikler og kommuniserer ned til resten av organisasjonen',
      'Et sett med kjerneverdier og atferdsnormer som beskriver ønsket kultur i virksomheten',
      'Et felles målbilde der avdelinger koordinerer sine delmål mot et overordnet resultat',
    ],
    correct: 0,
    explain: 'Felles visjon handler om å bygge en ekte, delt forståelse av hva organisasjonen ønsker å skape – en visjon som folk genuint deler og forplikter seg til, ikke bare en slogan som er pålagt ovenfra.',
  },
  {
    cat: 'ou_tql',
    catLabel: 'OU, TKL, LEAN og Senge',
    q: 'Hvilke OU-verktøy brukes for å fremme organisasjonsutvikling i praksis?',
    opts: [
      'Lønnssamtaler, stillingsbeskrivelser og formelle ansettelsesprosedyrer',
      'Prosjektplaner, milepælsrapporter og risikoanalyser for endringsinitiativer',
      'Organisasjonskart, rolleavklaringer og styringsmodeller for teamstruktur',
      'Medarbeidersamtaler, kompetanseutvikling og medarbeiderundersøkelser',
    ],
    correct: 3,
    explain: 'Konkrete OU-verktøy inkluderer: medarbeidersamtaler (systematisk dialog), kompetanseutvikling (kurs, hospitering) og medarbeiderundersøkelser (kartlegge trivsel og utfordringer).',
  },
  {
    cat: 'endring_def',
    catLabel: 'Endringsledelse – grunnlag',
    q: 'Hva er prestasjonsledelse i OU-sammenheng?',
    opts: [
      'En helhetlig tilnærming for å sette mål, følge opp og utvikle ansattes prestasjoner kontinuerlig',
      'Et system for å rapportere og håndtere avvik i produktivitet og måloppnåelse',
      'Et lønns- og insentivsystem koblet til individuelle resultater og teamprestasjoner',
      'En metode for å kartlegge kompetansegap og planlegge opplæringstiltak i organisasjonen',
    ],
    correct: 0,
    explain: 'Prestasjonsledelse er en helhetlig tilnærming for å sette tydelige mål (SMART), følge opp, gi tilbakemelding og coache ansatte til kontinuerlig utvikling og forbedrede prestasjoner.',
  },
  {
    cat: 'modeller',
    catLabel: 'Kotters og Lewins modeller',
    q: 'Hva menes med "fryse"-fasen i Lewins modell?',
    opts: [
      'Å avslutte endringsprosessen formelt og overlevere ansvar til linjeledelsen',
      'Å stabilisere organisasjonen etter endringen ved å sette alle videre initiativ på vent',
      'Å dokumentere erfaringene fra endringsprosessen og evaluere resultatene grundig',
      'Å forankre den nye atferden og de nye rutinene som den nye normalen i organisasjonen',
    ],
    correct: 3,
    explain: 'Fryse-fasen handler om å konsolidere og forankre endringene – de nye arbeidsmetodene, verdiene og atferdene skal bli den nye standarden som tas for gitt, ikke midlertidige unntak.',
  },
  {
    cat: 'ou_tql',
    catLabel: 'OU, TKL, LEAN og Senge',
    q: 'Hva er "mentale modeller" som Senges disiplin?',
    opts: [
      'Bevissthet om og utfordring av egne og kollektive antakelser og forestillinger som påvirker beslutninger',
      'Psykologiske profiler som kartlegger ansattes personlighetstyper og beslutningsstiler',
      'Strukturerte tankemodeller som teamet bruker for å planlegge og gjennomføre prosjekter',
      'Møtemetodikk og fasiliterte prosesser som fremmer åpen dialog og felles problemløsning',
    ],
    correct: 0,
    explain: 'Mentale modeller er de dype antakelsene, generaliseringene og bildene vi bærer med oss som påvirker hva vi ser og how vi handler. Disiplinen handler om å bli bevisst på og utfordre disse for bedre beslutninger.',
  },
  {
    cat: 'ou_tql',
    catLabel: 'OU, TKL, LEAN og Senge',
    q: 'Hva er "læring i team" som Senges disiplin?',
    opts: [
      'At teammedlemmer deler fagkunnskap og roterer på oppgaver for å bygge bredere kompetanse',
      'At teamet setter av tid til felles refleksjon og erfaringsutveksling etter hvert prosjekt',
      'At leder legger til rette for individuell læring og veileder hvert teammedlem separat',
      'Kollektiv prosess der teamet tenker og lærer som en enhet – resulterer i bedre kollektive resultater enn summen av individene',
    ],
    correct: 3,
    explain: 'Læring i team handler om kollektiv tenkning og dialog – der teamets samlede intelligens overstiger summen av enkeltindividene. Dette krever evne til å sette til side antakelser og tenke fritt sammen.',
  },
  {
    cat: 'endring_def',
    catLabel: 'Endringsledelse – grunnlag',
    q: 'Hva er en prestasjonskultur?',
    opts: [
      'En kultur der forventninger er tydelige, ansatte har eierskap til mål og kontinuerlig forbedring er normen',
      'En kultur der individuelle bidrag synliggjøres og belønnes gjennom regelmessige tilbakemeldinger',
      'En kultur der toppledelsen setter ambisiøse mål og holder mellomledere ansvarlige for levering',
      'En kultur der resultater følges tett og avvik fra plan håndteres raskt og systematisk',
    ],
    correct: 0,
    explain: 'Prestasjonskultur innebærer at forventninger er tydelige og kjente, at ansatte tar eierskap til egne mål, og at kontinuerlig forbedring og læring er en naturlig del av hverdagen.',
  },
  {
    cat: 'modeller',
    catLabel: 'Kotters og Lewins modeller',
    q: 'Hva er "kortsiktige seire" i Kotters 8-trinnsmodell?',
    opts: [
      'Å skape synlige, raske resultater av endringen for å bevise at den virker og opprettholde motivasjonen',
      'Å nå delmål i endringsplanen og rapportere fremdrift til ledergruppa',
      'Å sikre at budsjettet overholdes i de første fasene og unngå kostnadsoverskridelser',
      'Å identifisere og løse tekniske problemer tidlig for å hindre forsinkelser i prosjektet',
    ],
    correct: 0,
    explain: 'Å planlegge og synliggjøre kortsiktige seire (trinn 6 hos Kotter) er avgjørende for å opprettholde motivasjon og tro på endringen blant ansatte – det viser at kursen er riktig.',
  },
];
