const QUIZ_META = {
  id: 'lom-ool-kultur',
  title: 'Organisasjonskultur',
  subtitle: 'Organisasjon og ledelse – Kap. 5',
  description: '37 spørsmål om Scheins kulturmodell, de 4 kulturtypene, subkulturer, gruppetenkning og Belbins 9 grupperoller.',
  cats: {
    schein:      { label: 'Scheins kulturmodell', color: '#8b5cf6' },
    kulturtyper: { label: 'De fire kulturtypene', color: '#3b82f6' },
    subkulturer: { label: 'Subkulturer og dynamikk', color: '#10b981' },
    belbin:      { label: 'Belbins grupperoller', color: '#f59e0b' },
  }
};

const QUESTIONS = [
  {
    cat: 'schein',
    catLabel: 'Scheins kulturmodell',
    q: 'Hvem utviklet den mest brukte definisjonen av organisasjonskultur som "et mønster av felles grunnleggende antakelser"?',
    opts: [
      'Peter Senge',
      'Edgar Schein',
      'Douglas McGregor',
      'Meredith Belbin',
    ],
    correct: 1,
    explain: 'Edgar Schein definerte organisasjonskultur som et mønster av felles grunnleggende antakelser som en gruppe har lært seg gjennom å løse problemer med ekstern tilpasning og intern integrasjon.',
  },
  {
    cat: 'schein',
    catLabel: 'Scheins kulturmodell',
    q: 'Hva er artefakter i Scheins kulturmodell?',
    opts: [
      'De dypeste, ubevisste antakelsene – forankret i organisasjonens grunnleggende tro på virkeligheten',
      'De synlige, overfladiske uttrykkene for kultur: symboler, ritualer, kleskode, kontorlandskap',
      'De offisielle verdiene ledelsen har vedtatt og kommunisert til hele organisasjonen',
      'De skriftlige normene og retningslinjene som er beskrevet i personalhåndboken',
    ],
    correct: 1,
    explain: 'Artefakter er det synlige og øverste nivået i Scheins modell – fysiske og atferdsmessige uttrykk for kulturen: logoer, ritualer, kleskode, kontorlandskap og språk.',
  },
  {
    cat: 'schein',
    catLabel: 'Scheins kulturmodell',
    q: 'Hvilke av følgende er eksempler på artefakter i Scheins kulturmodell?',
    opts: [
      'Kleskode, kontorlandskap og synlige symboler',
      'Grunnleggende antakelser om menneskelig natur',
      'Ritualer, seremonier og fellesarrangementer',
      'Delte normer for hva som er riktig og gal atferd',
    ],
    correct: [0, 2],
    explain: 'Artefakter er de synlige, konkrete uttrykkene for kulturen – kleskode, kontorlandskap, symboler, ritualer og seremonier. Grunnleggende antakelser er det dypeste nivået, og normer hører til verdier/normer-nivået.',
  },
  {
    cat: 'schein',
    catLabel: 'Scheins kulturmodell',
    q: 'Hva representerer "verdier og normer" som det midtre nivået i Scheins modell?',
    opts: [
      'Det lett observerbare laget – synlig for utenforstående gjennom symboler og ritualer',
      'Delte oppfatninger om hva som er riktig atferd – delvis bevisst og kan diskuteres',
      'Dype, ubevisste antakelser om virkeligheten som sjelden stilles spørsmål ved',
      'Formelle regler og prosedyrer som er nedskrevet i organisasjonens håndbøker',
    ],
    correct: 1,
    explain: 'Verdier og normer er det midtre nivået – felles oppfatninger om hva som er riktig, viktig og ønskelig atferd. De er delvis bevisste og kan diskuteres, men er ikke alltid synlige for utenforstående.',
  },
  {
    cat: 'schein',
    catLabel: 'Scheins kulturmodell',
    q: 'Hva er grunnleggende antakelser i Scheins kulturmodell?',
    opts: [
      'De synlige symbolene, ritualene og atferdsmønstrene som preger hverdagen i organisasjonen',
      'De nedskrevne kjerneverdiene som presenteres i årsrapporten og på nettsiden',
      'Dype, ubevisste antagelser om virkeligheten som tas fullstendig for gitt',
      'De formelle målene og strategiene som er vedtatt i organisasjonens strategiplan',
    ],
    correct: 2,
    explain: 'Grunnleggende antakelser er det dypeste og mest usynlige nivået – ubevisste antagelser om verden, mennesket og relasjoner som tas helt for gitt og sjelden stilles spørsmål ved.',
  },
  {
    cat: 'schein',
    catLabel: 'Scheins kulturmodell',
    q: 'Hva illustrerer isfjellmodellen i organisasjonskulturens kontekst?',
    opts: [
      'At organisasjonskultur er et fenomen som primært utvikler seg i store og etablerte bedrifter over tid',
      'At den synlige delen (artefakter) er liten, mens den usynlige delen (verdier, antakelser) er mye større og dypere',
      'At kulturen er stabil og tung å bevege – som et isfjell som driver sakte gjennom havet',
      'At ledelsen sjelden forstår hvilke kulturelle strømninger som faktisk preger organisasjonen',
    ],
    correct: 1,
    explain: 'Isfjellmodellen illustrerer at bare en liten del av kulturen er synlig (artefakter over vannflaten), mens den største og viktigste delen (verdier, normer og grunnleggende antakelser) er usynlig under overflaten.',
  },
  {
    cat: 'schein',
    catLabel: 'Scheins kulturmodell',
    q: 'Hva betyr ekstern tilpasning i Scheins kulturmodell?',
    opts: [
      'Å rekruttere nye medarbeidere utenfra for å tilføre organisasjonen friske perspektiver og faglig fornying',
      'At kulturen hjelper organisasjonen å forstå og tilpasse seg omgivelsene – marked, konkurrenter, samfunn',
      'At organisasjonen gradvis overtar verdier og praksiser fra bransjeledende konkurrenter',
      'At kulturen justeres fortløpende i takt med teknologiske endringer i omgivelsene',
    ],
    correct: 1,
    explain: 'Ekstern tilpasning handler om at kulturen gir felles forståelse for mål, strategi og metoder som hjelper organisasjonen navigere og tilpasse seg ytre omgivelser.',
  },
  {
    cat: 'schein',
    catLabel: 'Scheins kulturmodell',
    q: 'Hva betyr intern integrasjon i Scheins kulturmodell?',
    opts: [
      'At medarbeidere har samme stillingstittel og formelt sett lik myndighet i organisasjonen',
      'At kulturen skaper felles identitet, samhold og felles forståelse internt i organisasjonen',
      'At avdelingene benytter de samme IT-systemene og digitale arbeidsverktøyene',
      'At organisasjonen samler ansatte i ett felles fysisk lokale for å styrke samarbeidet',
    ],
    correct: 1,
    explain: 'Intern integrasjon innebærer at kulturen skaper et felles "vi" – felles identitet, kommunikasjonsmåter, grenser for inn- og utgrupper, og felles forståelse for makt og status.',
  },
  {
    cat: 'schein',
    catLabel: 'Scheins kulturmodell',
    q: 'Hvilke to funksjoner fyller organisasjonskultur ifølge Schein?',
    opts: [
      'Ekstern tilpasning – hjelper organisasjonen forstå og tilpasse seg omgivelsene',
      'Hierarkisk kontroll – definerer maktforhold og beslutningsveier i organisasjonen',
      'Intern integrasjon – skaper felles identitet og samhold internt i organisasjonen',
      'Kulturell dominans – sikrer at én kultur vinner frem over konkurrerende subkulturer',
    ],
    correct: [0, 2],
    explain: 'Scheins to hovefunksjoner for organisasjonskultur er ekstern tilpasning (hjelpe organisasjonen navigere omgivelsene) og intern integrasjon (skape et felles "vi" med felles identitet og samhold).',
  },
  {
    type: 'order',
    cat: 'schein',
    catLabel: 'Scheins kulturmodell',
    q: 'Plasser de tre lagene i Scheins kulturmodell i riktig rekkefølge. Det mest synlige laget øverst, det dypeste laget nederst.',
    items: [
      'Grunnleggende antakelser',
      'Verdier og normer',
      'Artefakter',
    ],
    explain: 'Scheins kulturmodell fra overflate til dybde: Artefakter (synlige symboler og ritualer) øverst → Verdier og normer (delvis bevisste) i midten → Grunnleggende antakelser (ubevisste, tas for gitt) dypest.',
  },
  {
    cat: 'kulturtyper',
    catLabel: 'De fire kulturtypene',
    q: 'Hva kjennetegner klankultur?',
    opts: [
      'Sterk resultatorientering med fokus på konkurranse, salgsmål og markedsandeler',
      'Rigid hierarki med klare regler, prosedyrer og systematisk kontroll av atferd',
      'Familie-lignende atmosfære med høy lojalitet, samarbeid og omsorg for ansatte',
      'Innovasjon, risikovilje og kreativitet som prioriteres fremfor stabilitet og forutsigbarhet',
    ],
    correct: 2,
    explain: 'Klankultur er kjennetegnet av et familie-lignende miljø med sterk lojalitet, samarbeid, deltakelse og omsorg for de ansatte. Ledere fungerer som mentorer.',
  },
  {
    cat: 'kulturtyper',
    catLabel: 'De fire kulturtypene',
    q: 'Hva kjennetegner adhockultur?',
    opts: [
      'Stabilitet, kontroll og klare prosedyrer som sikrer forutsigbar og effektiv drift',
      'Sterk konkurranseorientering mot markedet og kundesegmentene',
      'Innovasjon, kreativitet, fleksibilitet og villighet til å ta risiko',
      'Familie-lignende samhold og omsorg for ansattes trivsel og faglige utvikling',
    ],
    correct: 2,
    explain: 'Adhockultur kjennetegnes av dynamisme, kreativitet og risikovilje. Organisasjonen er villig til å prøve nytt og aksepterer usikkerhet. Typisk i oppstartsbedrifter og FoU-miljøer.',
  },
  {
    cat: 'kulturtyper',
    catLabel: 'De fire kulturtypene',
    q: 'Hva kjennetegner hierarkikultur?',
    opts: [
      'Innovasjon og kreativitet – organisasjonen belønner nytenkning og eksperimentering',
      'Formelle regler, klare prosedyrer, stabilitet og effektivitet gjennom kontroll',
      'Sterkt fokus på å vinne i markedet og oppnå bedre resultater enn konkurrentene',
      'Uformell, familie-lignende atmosfære der samhold og trivsel settes høyt',
    ],
    correct: 1,
    explain: 'Hierarkikultur vektlegger formelle regler, prosedyrer, standardisering og stabilitet. Lederne er koordinatorer og organisatorer. Typisk i offentlige etater og tradisjonelle produksjonsbedrifter.',
  },
  {
    cat: 'kulturtyper',
    catLabel: 'De fire kulturtypene',
    q: 'Hva kjennetegner markedskultur?',
    opts: [
      'Omsorg for ansattes trivsel og et uformelt, fleksibelt arbeidsmiljø',
      'Kreativitet og vilje til å ta risiko for å drive frem innovasjon',
      'Resultatorientering, konkurranse og fokus på å nå markedsmål',
      'Strenge regler, prosedyrer og et tydelig hierarki',
    ],
    correct: 2,
    explain: 'Markedskultur er resultat- og konkurranseorientert. Fokuset er på å nå mål, vinne markedsandeler og slå konkurrentene. Ledere er pådrivere og krevende.',
  },
  {
    cat: 'kulturtyper',
    catLabel: 'De fire kulturtypene',
    q: 'Hvilken kulturtype passer best for en offentlig etat med mange regler og standardiserte prosedyrer?',
    opts: [
      'Adhockultur',
      'Klankultur',
      'Hierarkikultur',
      'Markedskultur',
    ],
    correct: 2,
    explain: 'Hierarkikultur med vekt på regler, prosedyrer, stabilitet og kontroll passer best for offentlige etater og organisasjoner som krever høy grad av standardisering.',
  },
  {
    cat: 'kulturtyper',
    catLabel: 'De fire kulturtypene',
    q: 'Hvilken kulturtype vil typisk dominere i en startup-bedrift som utvikler ny teknologi?',
    opts: [
      'Hierarkikultur',
      'Markedskultur',
      'Klankultur',
      'Adhockultur',
    ],
    correct: 3,
    explain: 'Adhockultur med vekt på innovasjon, fleksibilitet, risikovilje og kreativitet er typisk for oppstartsbedrifter og teknologiselskaper i vekst.',
  },
  {
    type: 'sort',
    cat: 'kulturtyper',
    catLabel: 'De fire kulturtypene',
    q: 'Sorter hvert kjennetegn til riktig kulturtype.',
    bins: [
      { id: 'klan',     label: 'Klankultur',    color: '#10b981' },
      { id: 'adhoc',    label: 'Adhockultur',    color: '#8b5cf6' },
      { id: 'hierarki', label: 'Hierarkikultur', color: '#3b82f6' },
      { id: 'marked',   label: 'Markedskultur',  color: '#ef4444' },
    ],
    items: [
      { text: 'Familie-lignende samhold',     bin: 'klan'     },
      { text: 'Innovasjon og risikovilje',    bin: 'adhoc'    },
      { text: 'Regler og prosedyrer',         bin: 'hierarki' },
      { text: 'Konkurranseorientering',       bin: 'marked'   },
      { text: 'Mentorledelse',                bin: 'klan'     },
      { text: 'Kreativitet og fleksibilitet', bin: 'adhoc'    },
      { text: 'Standardisering og kontroll',  bin: 'hierarki' },
      { text: 'Fokus på markedsandeler',      bin: 'marked'   },
    ],
    explain: 'Klankultur: familie-samhold, mentorledelse. Adhockultur: innovasjon, risikovilje, kreativitet. Hierarkikultur: regler, prosedyrer, standardisering og kontroll. Markedskultur: konkurranse, markedsandeler, resultatorientering.',
  },
  {
    cat: 'subkulturer',
    catLabel: 'Subkulturer og dynamikk',
    q: 'Hva er en subkultur i en organisasjon?',
    opts: [
      'En svakere og midlertidig kulturvariant som gradvis løses opp og absorberes av dominantkulturen',
      'En distinkt kultur som eksisterer innenfor den dominerende organisasjonskulturen – gjerne i en avdeling eller faggruppe',
      'En kulturvariant som primært oppstår i store multinasjonale selskaper med mange nasjonale avdelinger',
      'En uformell sosial gruppe med egne aktiviteter, men uten varig innvirkning på organisasjonens kultur',
    ],
    correct: 1,
    explain: 'Subkulturer er distinkte kulturer som oppstår i undergrupper av organisasjonen (avdelinger, faggrupper, lokasjoner). De kan sameksistere med og styrke dominantkulturen.',
  },
  {
    cat: 'subkulturer',
    catLabel: 'Subkulturer og dynamikk',
    q: 'Hva kjennetegner en motkultur i en organisasjon?',
    opts: [
      'En kultur som aktivt utfordrer og motarbeider den dominerende organisasjonskulturen',
      'En kultur som støtter og forsterker organisasjonens offisielle verdier og normer',
      'En kultur som vokser frem i geografisk spredte avdelinger med begrenset kontakt med hovedkontoret',
      'En midlertidig kulturvariant som oppstår under omstillingsprosesser og forsvinner etterpå',
    ],
    correct: 0,
    explain: 'En motkultur er en gruppe som ikke bare er annerledes, men som aktivt motarbeider den dominerende kulturen. Dette kan hemme endringsprosesser og skape konflikter.',
  },
  {
    cat: 'subkulturer',
    catLabel: 'Subkulturer og dynamikk',
    q: 'Hva er gruppetenkning (groupthink) ifølge Irving Janis?',
    opts: [
      'En gruppebasert teknikk for effektiv idéinnsamling og kreativ problemløsning i team',
      'En kognitiv evne til å koordinere tankeprosesser og handle som én enhet i krevende situasjoner',
      'En fasilitert teknikk for å bygge felles forståelse og styrke teamkulturen i en gruppe',
      'Et fenomen der press for konformitet i gruppen undertrykker kritisk tenkning og fører til dårlige beslutninger',
    ],
    correct: 3,
    explain: 'Gruppetenkning (Janis) oppstår når press for konsensus i gruppen undertrykker kritisk tenkning. Gruppen unngår uenighet, og dette kan føre til svært dårlige beslutninger – som ved Bay of Pigs-invasjonen.',
  },
  {
    cat: 'subkulturer',
    catLabel: 'Subkulturer og dynamikk',
    q: 'Hvilke to kjennetegn er typiske for gruppetenkning ifølge Janis?',
    opts: [
      'Gruppen undertrykker avvikende meninger for å opprettholde enighet',
      'Gruppen søker aktivt fageksperter utenfra for å utfordre egne antagelser',
      'Uenighet og åpen konflikt preger prosessen og fører til langsomme beslutninger',
      'Gruppen tror den er ufeilbarlig og at egne beslutninger alltid er riktige',
    ],
    correct: [0, 3],
    explain: 'To typiske kjennetegn på gruppetenkning: (1) press for konformitet undertrykker avvikende meninger, og (2) en illusjon om ufeilbarlighet – gruppen kritiserer ikke egne beslutninger.',
  },
  {
    cat: 'subkulturer',
    catLabel: 'Subkulturer og dynamikk',
    q: 'Hva er dysfunksjonell organisasjonskultur?',
    opts: [
      'En kultur som hemmer organisasjonens effektivitet, trivsel og måloppnåelse',
      'En kultur som mangler skriftlige verdierklæringer og formelle normdokumenter',
      'En sterk, ekskluderende kultur som gjør det vanskelig for nye medarbeidere å bli inkludert',
      'En kulturvariant som preger organisasjoner i alvorlig finansiell krise eller omstrukturering',
    ],
    correct: 0,
    explain: 'Dysfunksjonell kultur er en kultur som aktivt hemmer organisasjonens evne til å fungere godt – f.eks. gjennom taushetsnormer, fryktkultur, nepotisme eller gruppetenkning.',
  },
  {
    cat: 'subkulturer',
    catLabel: 'Subkulturer og dynamikk',
    q: 'Hvilken rolle spiller leder i kulturbygging?',
    opts: [
      'Ledere har begrenset innflytelse på kulturen – den formes primært av de ansattes daglige samhandling',
      'Kulturen formes av medarbeiderne i fellesskap og er ikke særlig påvirket av enkeltpersoner',
      'Ledere påvirker kulturen ved å utarbeide nye retningslinjer og oppdatere organisasjonens håndbøker',
      'Ledere setter eksempel, definerer hva som belønnes og straffer, og former ritualene i organisasjonen',
    ],
    correct: 3,
    explain: 'Ledere er de viktigste kulturbærerne og -skaperne. Gjennom hva de prioriterer, belønner, straffer, sier og gjør, sender de kontinuerlige signaler om hva som er viktig i organisasjonen.',
  },
  {
    cat: 'subkulturer',
    catLabel: 'Subkulturer og dynamikk',
    q: 'Hva kan seleksjon og rekruttering gjøre med organisasjonskulturen?',
    opts: [
      'Rekruttering av like-minded kandidater kan forsterke eksisterende kultur; mangfold kan utfordre og fornye den',
      'Rekruttering har liten kulturell effekt – kulturen formes av strukturer og systemer, ikke enkeltpersoner',
      'Nyansatte går gjennom sosialisering og tilpasser seg kulturen uten å påvirke den nevneverdig',
      'Seleksjon bør balansere mellom faglige kvalifikasjoner og kulturell tilpasning – ikke prioritere én faktor',
    ],
    correct: 0,
    explain: 'Rekruttering er et viktig kulturvirkemiddel. Å ansette folk som "passer inn" forsterker kulturen, mens bevisst rekruttering av mangfold kan bidra til kulturell fornyelse.',
  },
  {
    cat: 'belbin',
    catLabel: 'Belbins grupperoller',
    q: 'Hvor mange grupperoller identifiserte Meredith Belbin i sin forskning?',
    opts: [
      '6',
      '7',
      '8',
      '9',
    ],
    correct: 3,
    explain: 'Belbin identifiserte 9 grupperoller fordelt på tre kategorier: handlingsroller, sosiale roller og reflekterende (tanke-)roller.',
  },
  {
    cat: 'belbin',
    catLabel: 'Belbins grupperoller',
    q: 'Hvilke tre roller utgjør handlingsrollene i Belbins modell?',
    opts: [
      'Idéskaper, Vurderer og Spesialist',
      'Koordinator, Lagspiller og Ressurskontakt',
      'Iverksetter, Avslutter og Pådriver',
      'Koordinator, Iverksetter og Idéskaper',
    ],
    correct: 2,
    explain: 'Belbins handlingsroller er Iverksetter (strukturerer og gjennomfører), Avslutter (kvalitetssikrer og ferdigstiller) og Pådriver (driver gruppen fremover med energi).',
  },
  {
    cat: 'belbin',
    catLabel: 'Belbins grupperoller',
    q: 'Hvilke tre roller utgjør de sosiale rollene i Belbins modell?',
    opts: [
      'Iverksetter, Avslutter og Pådriver',
      'Idéskaper, Vurderer og Spesialist',
      'Koordinator, Lagspiller og Ressurskontakt',
      'Pådriver, Koordinator og Avslutter',
    ],
    correct: 2,
    explain: 'Belbins sosiale roller er Koordinator (delegerer og fasiliterer), Lagspiller (støtter og samarbeider) og Ressurskontakt (henter ressurser og kontakter utenfra).',
  },
  {
    cat: 'belbin',
    catLabel: 'Belbins grupperoller',
    q: 'Hvilke tre roller utgjør de reflekterende rollene i Belbins modell?',
    opts: [
      'Koordinator, Lagspiller og Ressurskontakt',
      'Pådriver, Idéskaper og Koordinator',
      'Iverksetter, Avslutter og Pådriver',
      'Idéskaper, Vurderer og Spesialist',
    ],
    correct: 3,
    explain: 'Belbins reflekterende roller er Idéskaper (kreativ problemløser), Vurderer (kritisk analytiker) og Spesialist (dyp fagekspertise på et smalt felt).',
  },
  {
    cat: 'belbin',
    catLabel: 'Belbins grupperoller',
    q: 'Hva er kjennetegnet på rollen "Idéskaper" i Belbins modell?',
    opts: [
      'Følger opp detaljer og sikrer at arbeidet er ferdig og feilfritt ved leveranse',
      'Bygger og vedlikeholder et nettverk av kontakter og ressurser utenfor gruppen',
      'Kreativ tenker som genererer originale ideer og løser vanskelige problemer',
      'Koordinerer gruppens arbeid, tydeliggjør mål og delegerer oppgaver til rette personer',
    ],
    correct: 2,
    explain: 'Idéskaperen er den kreative og ukonvensjonelle tenkeren i gruppen – genererer originale ideer og løser vanskelige problemer, men kan være dårlig på å kommunisere ideene til andre.',
  },
  {
    cat: 'belbin',
    catLabel: 'Belbins grupperoller',
    q: 'Hva kjennetegner Idéskaperen i Belbins modell?',
    opts: [
      'Genererer originale og kreative ideer for å løse vanskelige problemer',
      'Sikrer at gruppen følger tidsplanen og ikke mister fokus på målet',
      'Kan ha utfordringer med å kommunisere ideene sine til resten av gruppen',
      'Ferdigstiller arbeidet og sikrer høy kvalitet og presisjon ved leveranse',
    ],
    correct: [0, 2],
    explain: 'Idéskaperen er kreativ og genererer originale ideer, men har ofte utfordringer med å kommunisere dem tydelig til andre. Å holde tidsplan er Pådriverens rolle, og å ferdigstille er Avsluterens.',
  },
  {
    cat: 'belbin',
    catLabel: 'Belbins grupperoller',
    q: 'Hva er kjennetegnet på rollen "Avslutter" i Belbins modell?',
    opts: [
      'Kvalitetssikrer arbeidet, følger opp detaljer og sikrer at alt er ferdig og feilfritt',
      'Oppsummerer diskusjoner og sørger for at gruppen tar beslutninger og beveger seg videre',
      'Megler mellom gruppemedlemmene og løser opp i konflikter som oppstår underveis',
      'Påtar seg de mest komplekse deloppgavene og driver dem frem mot ferdigstilling',
    ],
    correct: 0,
    explain: 'Avslutteren er perfeksjonisten i gruppen – følger opp detaljer, søker etter feil og mangler, og sørger for at arbeidet holder høy kvalitet ved leveranse.',
  },
  {
    cat: 'belbin',
    catLabel: 'Belbins grupperoller',
    q: 'Hva er kjennetegnet på rollen "Koordinator" i Belbins modell?',
    opts: [
      'Leder gruppen ved å tydeliggjøre mål, delegere oppgaver og fremme felles beslutninger',
      'Sørger for at fremdrift og arbeidsflyt holder seg på sporet gjennom hele prosjektperioden',
      'Sikrer at leveranser fra ulike bidragsytere henger sammen og leveres koordinert',
      'Kontrollerer at etablerte regler, prosedyrer og standarder etterleves i gruppen',
    ],
    correct: 0,
    explain: 'Koordinatoren er en moden og trygg ledertype som tydeliggjør mål, delegerer oppgaver til riktige mennesker og fremmer samarbeid og felles beslutninger i gruppen.',
  },
  {
    cat: 'belbin',
    catLabel: 'Belbins grupperoller',
    q: 'Hva er kjennetegnet på rollen "Ressurskontakt" i Belbins modell?',
    opts: [
      'Utforskende og entusiastisk – henter inn kontakter, ideer og ressurser utenfra gruppen',
      'Besitter dyp faglig spesialistkompetanse og bidrar med inngående kunnskap på et smalt felt',
      'Holder oversikt over prosjektets budsjett og sørger for forsvarlig ressursbruk',
      'Kartlegger gruppens samlede kompetanse og foreslår hvordan ressursene bør fordeles',
    ],
    correct: 0,
    explain: 'Ressurskontakten er utadvendt og entusiastisk – et nettverk av kontakter utenfor gruppen og henter inn impulser, ideer og ressurser som kan hjelpe gruppen fremover.',
  },
  {
    cat: 'belbin',
    catLabel: 'Belbins grupperoller',
    q: 'Hva er kjennetegnet på rollen "Vurderer" i Belbins modell?',
    opts: [
      'Strategisk og kritisk analytiker som vurderer ideer objektivt og oppdager svakheter',
      'Engasjert og kreativ bidragsyter som genererer et bredt spekter av originale løsningsforslag',
      'Evaluerer gruppemedlemmenes innsats og gir konstruktiv tilbakemelding på prestasjoner',
      'Fatter hurtige og selvstendige beslutninger når gruppen er under tidspress',
    ],
    correct: 0,
    explain: 'Vurdereren er den strategiske, kritiske analytikeren. Er dyktig til å vurdere ideer og forslag objektivt, oppdager svakheter og hindrer dårlige beslutninger – men kan oppfattes som kritisk og kynisk.',
  },
  {
    type: 'sort',
    cat: 'belbin',
    catLabel: 'Belbins grupperoller',
    q: 'Sorter hver av Belbins 9 roller i riktig kategori.',
    bins: [
      { id: 'handling', label: 'Handlingsroller',     color: '#ef4444' },
      { id: 'sosial',   label: 'Sosiale roller',      color: '#3b82f6' },
      { id: 'tanke',    label: 'Reflekterende roller', color: '#8b5cf6' },
    ],
    items: [
      { text: 'Iverksetter',    bin: 'handling' },
      { text: 'Avslutter',      bin: 'handling' },
      { text: 'Pådriver',       bin: 'handling' },
      { text: 'Koordinator',    bin: 'sosial'   },
      { text: 'Lagspiller',     bin: 'sosial'   },
      { text: 'Ressurskontakt', bin: 'sosial'   },
      { text: 'Idéskaper',      bin: 'tanke'    },
      { text: 'Vurderer',       bin: 'tanke'    },
      { text: 'Spesialist',     bin: 'tanke'    },
    ],
    explain: 'Handlingsroller: Iverksetter, Avslutter, Pådriver. Sosiale roller: Koordinator, Lagspiller, Ressurskontakt. Reflekterende (tanke-)roller: Idéskaper, Vurderer, Spesialist.',
  },
  {
    cat: 'schein',
    catLabel: 'Scheins kulturmodell',
    q: 'Hvilken utfordring møter man ved kulturendring ifølge Scheins modell?',
    opts: [
      'De grunnleggende antakelsene er ubevisste og tas for gitt – dermed svært vanskelig å endre',
      'Det er enkelt å endre kulturen ved å formulere og kommunisere nye verdier til de ansatte',
      'Kulturen er relativt stabil, men kan gradvis justeres gjennom målrettet lederskap over tid',
      'Artefaktene er de vanskeligste elementene å endre; verdier og antakelser lar seg forme raskt',
    ],
    correct: 0,
    explain: 'De grunnleggende antakelsene er det dypeste og mest resistente nivået. De er ubevisste og tas for gitt, noe som gjør kulturendring krevende og tidkrevende – man kan ikke bare skrive nye verdier.',
  },
  {
    cat: 'kulturtyper',
    catLabel: 'De fire kulturtypene',
    q: 'En bedrift som fokuserer sterkt på å slå konkurrentene, nå salgsmål og øke markedsandelen, kjennetegnes av hvilken kulturtype?',
    opts: [
      'Klankultur',
      'Adhockultur',
      'Hierarkikultur',
      'Markedskultur',
    ],
    correct: 3,
    explain: 'Markedskultur kjennetegnes av sterk resultatorientering og konkurranseinstinkt – fokus på å nå mål, vinne markedsandeler og overgå konkurrentene.',
  },
];
