const QUIZ_META = {
  id: 'lom-ool-ledelse',
  title: 'Lederstil og organisasjon',
  subtitle: 'LØM Fagskole · Supplement',
  description: '30 spørsmål om lederstil, organisasjonsformer, kommunikasjon og endringspsykologi.',
  cats: {
    lederstil:     { label: 'Lederstil', color: '#8b5cf6' },
    org_former:    { label: 'Organisasjonsformer', color: '#3b82f6' },
    kommunikasjon: { label: 'Kommunikasjon', color: '#10b981' },
    supplement:    { label: 'Supplement', color: '#f59e0b' },
  }
};

const QUESTIONS = [
  {
    cat: 'lederstil',
    catLabel: 'Lederstil',
    q: 'Hva kjennetegner en demokratisk leder?',
    opts: [
      'Tar alle beslutninger alene uten konsultasjon',
      'Involverer medarbeiderne i beslutningsprosessen, men beholder det endelige ansvaret',
      'Overlater all beslutningsmyndighet fullt ut til de ansatte',
      'Styrer utelukkende gjennom belønning og straff',
    ],
    correct: 1,
    explain: 'En demokratisk leder involverer medarbeiderne i beslutningsprosessen, men beholder det formelle ansvaret. Gir økt motivasjon og bedre beslutningskvalitet.',
  },
  {
    cat: 'lederstil',
    catLabel: 'Lederstil',
    q: 'Hva kjennetegner laissez-faire-lederstil?',
    opts: [
      'Streng kontroll og klare ordrer fra lederen',
      'Demokratisk deltakelse i alle beslutninger',
      'Lederen delegerer fullt ut og griper minimalt inn i medarbeidernes arbeid',
      'Lederen fokuserer på transaksjonelle belønninger og straff',
    ],
    correct: 2,
    explain: 'Laissez-faire («la det skure») betyr at lederen i stor grad lar medarbeiderne styre seg selv og griper minimalt inn. Kan fungere godt for svært selvgående eksperter.',
  },
  {
    cat: 'lederstil',
    catLabel: 'Lederstil',
    q: 'Hersey og Blanchards situasjonsledelse opererer med fire modenhetsnivåer. Hva kjennetegner M1?',
    opts: [
      'Høy kompetanse og høy motivasjon – selvgående medarbeider',
      'Lav kompetanse, men høy motivasjon – entusiastisk nybegynner',
      'Høy kompetanse, men lav motivasjon – desillusjonert ekspert',
      'Lav kompetanse og lav motivasjon – umotivert nybegynner',
    ],
    correct: 1,
    explain: 'M1 = lav kompetanse, høy motivasjon (entusiastisk nybegynner). Anbefalt lederstil er instruerende (S1): fortell nøyaktig hva som skal gjøres og hvordan.',
  },
  {
    cat: 'lederstil',
    catLabel: 'Lederstil',
    q: 'Hvilken lederstil anbefaler Hersey & Blanchard for en medarbeider på M4-nivå (høy kompetanse og høy motivasjon)?',
    opts: [
      'Instruerende – fortell nøyaktig hva som skal gjøres',
      'Coachende – gi mye veiledning og støtte',
      'Støttende – oppmuntre og lytte aktivt',
      'Delegerende – gi ansvar og trekk deg tilbake',
    ],
    correct: 3,
    explain: 'M4 (høy kompetanse, høy motivasjon) = delegerende lederstil (S4). Medarbeideren er selvgående og trenger lite styring eller støtte.',
  },
  {
    cat: 'lederstil',
    catLabel: 'Lederstil',
    q: 'Hva skiller transformasjonsledelse fra transaksjonsledelse?',
    opts: [
      'Transformasjonsledelse bruker belønning og straff; transaksjonsledelse inspirerer gjennom visjon',
      'Transformasjonsledelse inspirerer og endrer verdier; transaksjonsledelse baserer seg på avtaler og belønning',
      'Transaksjonsledelse er egnet for krisetider; transformasjonsledelse for stabil drift',
      'Det er ingen vesentlig forskjell – begge handler om å nå fastsatte mål',
    ],
    correct: 1,
    explain: 'Transformasjonsledelse motiverer gjennom visjon, verdier og inspirasjon, og skaper indre motivasjon. Transaksjonsledelse baserer seg på klare avtaler, mål og ytre belønning/straff.',
  },
  {
    cat: 'lederstil',
    catLabel: 'Lederstil',
    q: 'Hva er coaching i ledersammenheng?',
    opts: [
      'En autoritær lederstil der lederen gir klare instrukser',
      'En prosess der lederen hjelper medarbeideren til å finne egne løsninger gjennom åpne spørsmål og refleksjon',
      'En belønningsstrategi basert på bonus og provisjon',
      'Et verktøy for å kontrollere medarbeidernes prestasjoner mot fastsatte KPI-er',
    ],
    correct: 1,
    explain: 'Coaching handler om å stille åpne spørsmål og skape refleksjon slik at medarbeideren selv finner løsninger og utvikler sin kompetanse. Lederen er fasilitator, ikke ekspert.',
  },
  {
    cat: 'lederstil',
    catLabel: 'Lederstil',
    q: 'Hva er hensikten med medarbeidersamtalen?',
    opts: [
      'Å gi medarbeideren en formell advarsel ved behov',
      'Å evaluere prestasjoner, sette mål og avklare utviklingsbehov i en planlagt toveis dialog',
      'Å informere om nye arbeidsoppgaver uten dialog fra medarbeiderens side',
      'Å fastsette lønn og bonusnivå for kommende periode',
    ],
    correct: 1,
    explain: 'Medarbeidersamtalen er et planlagt, toveis møte der leder og medarbeider evaluerer forrige periode, setter mål og planlegger utvikling. Begge parter forbereder seg.',
  },
  {
    cat: 'lederstil',
    catLabel: 'Lederstil',
    q: 'Hva kjennetegner konstruktiv feedback?',
    opts: [
      'Den er generell og upersonlig for å unngå konflikter',
      'Den fokuserer på personens egenskaper, ikke konkret atferd',
      'Den beskriver konkret observert atferd, konsekvenser og foreslår ønsket endring',
      'Den gis kun skriftlig for å sikre dokumentasjon',
    ],
    correct: 2,
    explain: 'Konstruktiv feedback er konkret, beskriver observert atferd og dens konsekvenser, og antyder hva som bør endres – uten å angripe personen. Fokus på atferd, ikke person.',
  },
  {
    cat: 'org_former',
    catLabel: 'Organisasjonsformer',
    q: 'Hva kjennetegner en linjestabsorganisasjon?',
    opts: [
      'Alle ansatte rapporterer til én og samme leder uansett funksjon',
      'Linjen har beslutningsmyndighet, mens staben er rådgivende uten beslutningsmyndighet',
      'Medarbeiderne er organisert i selvstyrte team med roterende ledelse',
      'Organisasjonen er delt inn i prosjekter med midlertidige lederroller',
    ],
    correct: 1,
    explain: 'I en linjestabsorganisasjon har linjen (leder→medarbeider) beslutningsmyndighet. Staben (f.eks. HR, økonomi, HMS) er faglig rådgivende uten instruksjonsmyndighet over linjen.',
  },
  {
    cat: 'org_former',
    catLabel: 'Organisasjonsformer',
    q: 'Hva er en sentral ulempe med matriseorganisering?',
    opts: [
      'Dårlig ressursutnyttelse på tvers av avdelinger og funksjoner',
      'Medarbeidere kan ha to ledere, noe som skaper uklar myndighet og lojalitetskonflikter',
      'Det er umulig å koordinere prosjekter på tvers av faggrupper',
      'Organisasjonen blir for rigid og mister evnen til å tilpasse seg endringer',
    ],
    correct: 1,
    explain: 'I en matriseorganisasjon har medarbeidere både en linjeleder og en prosjektleder. Dette kan gi uklare ansvarsforhold og lojalitetskonflikter – «to herrer å tjene».',
  },
  {
    cat: 'org_former',
    catLabel: 'Organisasjonsformer',
    q: 'Hva kjennetegner en prosjektorganisasjon?',
    opts: [
      'Permanent struktur med faste avdelinger og stabile hierarkier',
      'Midlertidig organisering rundt et bestemt mål, der deltakere hentes fra linjeorganisasjonen',
      'En flat organisasjon uten noen formelle ledere',
      'Organisering etter geografisk tilhørighet',
    ],
    correct: 1,
    explain: 'Prosjektorganisasjoner er midlertidige og samler ressurser fra ulike deler av virksomheten for å nå et spesifikt mål innen tid, budsjett og kvalitet. Oppløses etter avslutning.',
  },
  {
    cat: 'org_former',
    catLabel: 'Organisasjonsformer',
    q: 'Hva er forskjellen mellom formell og uformell organisasjon?',
    opts: [
      'Den formelle er det offisielle hierarkiet og strukturen; den uformelle er de faktiske relasjonene og kommunikasjonsmønstrene som oppstår naturlig',
      'Den formelle er liten og effektiv, den uformelle er stor og ineffektiv',
      'Den uformelle organisasjonen er alltid skadelig for bedriften og bør motarbeides',
      'Det er ingen reell forskjell i praksis – de er synonyme begreper',
    ],
    correct: 0,
    explain: 'Formell organisasjon = nedfelt i organisasjonskart og stillingsbeskrivelser. Uformell organisasjon = de sosiale nettverkene og kommunikasjonsmønstrene som oppstår naturlig blant ansatte.',
  },
  {
    cat: 'org_former',
    catLabel: 'Organisasjonsformer',
    q: 'Hva er EL&IT Forbundets funksjon?',
    opts: [
      'Å fastsette minstelønn for alle bransjer i Norge',
      'Å godkjenne og sertifisere elektrikere for autorisasjon',
      'Å representere arbeidstakerne i elektrobransjen og forhandle tariffavtaler på deres vegne',
      'Å utforme og vedta lover om arbeidsmiljø',
    ],
    correct: 2,
    explain: 'EL&IT Forbundet er fagforbundet for bl.a. elektrikere. De organiserer arbeidstakerne og forhandler tariffavtaler (bl.a. Landsoverenskomsten) overfor NHO Elektro.',
  },
  {
    cat: 'org_former',
    catLabel: 'Organisasjonsformer',
    q: 'Hva er NHO Elektro sin rolle?',
    opts: [
      'En offentlig etat som regulerer el-bransjen på vegne av myndighetene',
      'En interesseorganisasjon for strømleverandører og nettselskaper',
      'Et utdanningsorgan for elektriker-faget og fagopplæring',
      'Arbeidsgiverorganisasjonen for elektroentreprenører og NHOs forhandlingsmotpart overfor EL&IT Forbundet',
    ],
    correct: 3,
    explain: 'NHO Elektro er arbeidsgiverorganisasjonen for elektroentreprenører. De forhandler tariffavtaler, bl.a. Landsoverenskomsten, overfor EL&IT Forbundet.',
  },
  {
    cat: 'org_former',
    catLabel: 'Organisasjonsformer',
    q: 'Hva er endringskynisme i organisasjoner (Amundsen & Kongsvik)?',
    opts: [
      'Et sterkt ønske om rask og radikal endring blant ansatte',
      'En positiv, kritisk holdning til endring som stimulerer til bedre løsninger',
      'En kritisk og skeptisk holdning til planlagte endringer, basert på negative erfaringer fra tidligere endringsprosesser',
      'En strategi der ledelsen bevisst bremser endringstakten for å sikre kvalitet',
    ],
    correct: 2,
    explain: 'Endringskynisme (Amundsen & Kongsvik) er en kritisk og skeptisk holdning til endring. Den oppstår gjerne når ansatte gjentatte ganger opplever at endringer ikke gir lovede resultater, eller at de ikke involveres.',
  },
  {
    cat: 'org_former',
    catLabel: 'Organisasjonsformer',
    q: 'Hvilke fem dimensjoner beskriver graden av endringskynisme hos ansatte?',
    opts: [
      'Behov for endringen, endringshistorie, praksis i gjennomføringen, synliggjøring av resultater og grad av medvirkning',
      'Mål, strategi, ressurser, tid og kompetanse',
      'Visjon, misjon, verdier, kultur og formell struktur',
      'Planlegging, gjennomføring, evaluering, korrigering og forankring',
    ],
    correct: 0,
    explain: 'Amundsen & Kongsvik beskriver fem dimensjoner som forklarer endringskynisme: (1) behov for endring, (2) endringshistorie, (3) praksis i gjennomføringen, (4) synliggjøring av resultater, (5) grad av medvirkning.',
  },
  {
    cat: 'kommunikasjon',
    catLabel: 'Kommunikasjon',
    q: 'Hva er forskjellen mellom verbal og non-verbal kommunikasjon?',
    opts: [
      'Verbal er skriftlig, non-verbal er muntlig',
      'Verbal er alltid formell, non-verbal er alltid uformell',
      'Verbal bruker ord (muntlig og skriftlig); non-verbal bruker kroppsspråk, mimikk, tonefall og gester',
      'Non-verbal kommunikasjon er alltid mer troverdig enn verbal kommunikasjon',
    ],
    correct: 2,
    explain: 'Verbal kommunikasjon = ord (tale og skrift). Non-verbal = alt annet: kroppsspråk, mimikk, øyekontakt, tonefall, avstand og gester. Ca. 55–65 % av kommunikasjon er ikke-verbal.',
  },
  {
    cat: 'kommunikasjon',
    catLabel: 'Kommunikasjon',
    q: 'Hva er kommunikasjonsstøy?',
    opts: [
      'Høy musikk eller bråk på arbeidsplassen som forstyrrer konsentrasjonen',
      'For mye informasjon på én gang (informasjonsoverbelastning)',
      'Konflikter mellom ansatte som hindrer samarbeid',
      'Alt som forstyrrer eller forvrenger budskapet mellom sender og mottaker',
    ],
    correct: 3,
    explain: 'Støy i kommunikasjon er alt som hindrer budskapet i å nå frem slik det var ment – fysisk støy, språkbarrierer, følelsesmessige filtre, kulturelle misforståelser eller tekniske feil.',
  },
  {
    cat: 'kommunikasjon',
    catLabel: 'Kommunikasjon',
    q: 'Hva innebærer intern rekruttering fremfor ekstern rekruttering?',
    opts: [
      'Intern rekruttering betyr å hente kandidater fra egne ansatte – gir motivasjon og kulturkjennskap, men kan begrense nytenkning',
      'Intern rekruttering er alltid billigere og gir alltid bedre resultater',
      'Ekstern rekruttering er alltid best for å sikre ny og oppdatert kompetanse',
      'Intern rekruttering krever ikke utlysning eller stillingsbeskrivelse',
    ],
    correct: 0,
    explain: 'Intern rekruttering gir motivasjon (synlige karrieremuligheter) og god kulturforståelse. Ulempen er at det kan gi ensretting. Ekstern rekruttering bringer friske øyne og ny kompetanse, men krever mer onboarding.',
  },
  {
    cat: 'kommunikasjon',
    catLabel: 'Kommunikasjon',
    q: 'Hva er de fem effektene av å involvere ansatte i endringsprosesser?',
    opts: [
      'Reduserte kostnader, kortere tid, færre feil, høyere produktivitet og bedre dokumentasjon',
      'Kortere møter, færre konflikter, tydeligere roller, klarere prosedyrer og mer effektiv ressursbruk',
      'Lavere turnover, bedre rekruttering, sterkere merkevare, bedre kunderelasjoner og økt innovasjon',
      'Økt motivasjon, økt tilfredshet, bedre kvalitet på beslutninger, økt aksept for endringen og kompetanseheving',
    ],
    correct: 3,
    explain: 'De fem effektene av involvering: (1) økt motivasjon, (2) økt tilfredshet, (3) bedre beslutningskvalitet, (4) økt aksept for endringen, (5) kompetanseheving hos de involverte.',
  },
  {
    cat: 'kommunikasjon',
    catLabel: 'Kommunikasjon',
    q: 'Hva menes med konflikthåndtering i organisasjoner?',
    opts: [
      'Å identifisere, forstå og løse uenigheter på en konstruktiv måte som ivaretar relasjoner og organisasjonens mål',
      'Å unngå all konflikt gjennom streng disiplin og klare regler',
      'Å la partene avgjøre konflikter seg imellom uten lederinnblanding',
      'Å flytte én av partene til en annen avdeling for å unngå videre konfrontasjon',
    ],
    correct: 0,
    explain: 'God konflikthåndtering handler om å adressere konflikter konstruktivt: anerkjenne uenigheten, forstå begge parters perspektiv og finne løsninger som ivaretar relasjoner og produktivitet.',
  },
  {
    cat: 'kommunikasjon',
    catLabel: 'Kommunikasjon',
    q: 'Hva er delegering, og hva er en viktig forutsetning for at det skal fungere?',
    opts: [
      'Delegering er å kvitte seg med uønskede oppgaver; det krever ingen spesielle forutsetninger',
      'Delegering er kun egnet for rutineoppgaver uten risiko',
      'Delegering betyr at lederen alltid beholder den formelle myndigheten og bare ber andre utføre arbeidet',
      'Delegering er å overføre oppgaver og beslutningsmyndighet til medarbeidere; forutsetning: myndighet, ansvar og ressurser must følge med oppgaven',
    ],
    correct: 3,
    explain: 'Delegering innebærer å overføre oppgaver med tilhørende myndighet og ressurser. Lederen beholder det overordnede ansvaret (ansvar kan ikke delegeres), men myndigheten til å handle overføres.',
  },
  {
    cat: 'kommunikasjon',
    catLabel: 'Kommunikasjon',
    q: 'Hva er beste virkemiddel mot motstand mot endring, ifølge Kanter (1992)?',
    opts: [
      'Tvang og sanksjonering av dem som motsetter seg endringen',
      'Hyppig og enveis informasjon om endringens fordeler',
      'Tidlig og reell involvering av de berørte partene i planleggingen',
      'Å ansette kun endringsvillige medarbeidere',
    ],
    correct: 2,
    explain: 'Kanter (1992) viser at motstand mot endring reduseres mest effektivt gjennom tidlig og reell involvering av de berørte. Informasjon alene er ikke tilstrekkelig – folk vil ha innflytelse, ikke bare beskjed.',
  },
  {
    cat: 'supplement',
    catLabel: 'Supplement',
    q: 'Hvilken av følgende er IKKE blant de praktiske tiltakene for å øke motivasjon på arbeidsplassen?',
    opts: [
      'Gi anerkjennelse og ros for godt arbeid',
      'Sett tydelige og utfordrende, men oppnåelige mål',
      'Innfør strengere kontroll for å sikre at alle jobber tilstrekkelig',
      'Gi medarbeiderne autonomi og reell medbestemmelse',
    ],
    correct: 2,
    explain: 'Strengere kontroll reduserer typisk den indre motivasjonen (korrumperingseffekt). Anerkjennelse, tydelige mål, autonomi og meningsfulle oppgaver er dokumenterte tiltak for å øke motivasjonen.',
  },
  {
    cat: 'supplement',
    catLabel: 'Supplement',
    q: 'Hvilke fem effekter har organisasjonskulturen på medarbeidernes atferd?',
    opts: [
      'Tilhørighet, motivasjon, tillit, samarbeid/koordinering og styring (uformell kontroll)',
      'Lønnsforventning, arbeidstid, stillingsbetegnelse, hierarki og formell status',
      'Rekruttering, opplæring, prestasjon, belønning og avgang',
      'Strategi, struktur, system, stab og ferdigheter',
    ],
    correct: 0,
    explain: 'Organisasjonskultur påvirker atferd gjennom: (1) tilhørighet – vi-følelse og identitet, (2) motivasjon – stolthet og engasjement, (3) tillit – åpenhet og psykologisk trygghet, (4) samarbeid og koordinering, (5) styring – uformell kontroll uten skriftlige regler.',
  },
  {
    cat: 'supplement',
    catLabel: 'Supplement',
    q: 'Hva er en av de mest effektive måtene ledere kan bygge og bevare organisasjonskulturen?',
    opts: [
      'Ansette kun faglig kompetente kandidater uansett personlighet og verdier',
      'Ansette så raskt som mulig for å fylle kapasitetsgapet',
      'Rekruttere utelukkende fra konkurrentene for å hente inn beste praksis',
      'Velge kandidater som deler organisasjonens verdier og kulturelle forventninger',
    ],
    correct: 3,
    explain: 'Rekruttering er et av lederens viktigste kulturbyggingsverktøy. Å velge kandidater som deler organisasjonens verdier (cultural fit) bidrar til å bevare og forsterke kulturen over tid.',
  },
  {
    cat: 'supplement',
    catLabel: 'Supplement',
    q: 'Hva innebærer SMART-målsetting i personalarbeid?',
    opts: [
      'Mål skal være Spesifikke, Målbare, Aktuelle (relevante), Realistiske og Tidsbestemte',
      'Mål skal være Støttende, Motiverende, Autonome, Relevante og Troverdige',
      'Mål skal alltid formuleres av lederen uten innspill fra medarbeideren',
      'Mål skal fokusere utelukkende på kvantitative og finansielle resultater',
    ],
    correct: 0,
    explain: 'SMART = Spesifikke, Målbare, Aktuelle (relevante), Realistiske og Tidsbestemte. SMART-mål gjør det lettere å evaluere fremgang, skape klarhet og oppleve mestring.',
  },
  {
    cat: 'supplement',
    catLabel: 'Supplement',
    q: 'Hva er kompetansemobilisering (Lai)?',
    opts: [
      'Å sikre at ansattes eksisterende kompetanse faktisk brukes og utnyttes i jobben',
      'Å sende ansatte på kurs for å øke den formelle kompetansen',
      'Å rekruttere medarbeidere med høyere kompetanse enn stillingen krever',
      'Å kartlegge og dokumentere kompetansegap i organisasjonen',
    ],
    correct: 0,
    explain: 'Lai viser at det ikke er nok å ha kompetanse – det avgjørende er at kompetansen faktisk mobiliseres (tas i bruk) i arbeidsoppgavene. Uutnyttet kompetanse gir lavere motivasjon og høyere turnover.',
  },
  {
    cat: 'supplement',
    catLabel: 'Supplement',
    q: 'Thorsruds demokratiseringsprinsipper (industrielt demokrati) vektlegger at arbeidet bør gi medarbeideren:',
    opts: [
      'Høyest mulig lønn og prestasjonsbasert bonus',
      'Strenge og målbare prestasjonsbaserte mål for alle oppgaver',
      'Variasjon, mulighet for læring, ansvar, medbestemmelse og sosiale relasjoner',
      'Minimal innsats for maksimal belønning og frihet',
    ],
    correct: 2,
    explain: 'Thorsruds psykologiske jobbkrav innebærer at arbeidet bør gi: variasjon, læring, ansvar, medbestemmelse og sosiale relasjoner. Dette gir meningsfullhet og øker den indre motivasjonen.',
  },
  {
    cat: 'supplement',
    catLabel: 'Supplement',
    q: 'Hva menes med prososial motivasjon?',
    opts: [
      'Motivasjon som kommer fra ønsket om å hjelpe andre og gjøre noe som er godt for fellesskapet',
      'Motivasjon som er drevet av personlig karriereutvikling og lønn',
      'Motivasjon som er skapt gjennom sosiale medier og anerkjennelse fra omgivelsene',
      'Motivasjon som er knyttet til sosiale arrangementer på arbeidsplassen',
    ],
    correct: 0,
    explain: 'Prososial motivasjon er motivasjon som springer ut av et ønske om å bidra positivt for andre – kolleger, kunder eller samfunnet. Det er en av tre motivasjonstyper (indre, ytre og prososial).',
  },
];
