'use strict';
const QUIZ_META = {
  id: 'trh1ek',
  title: 'TRH-1EK – Avsluttende prøve',
  subtitle: 'Quiz Elektroniske (Bjørns)',
  cats: {
    minne:        { label: 'Dataminne',              color: '#5c7cfa' },
    mcu:          { label: 'Mikrokontroller',         color: '#f59e0b' },
    tallsystemer: { label: 'Tallsystemer',            color: '#10b981' },
    analog:       { label: 'Analog elektronikk',      color: '#f472b6' },
    digital:      { label: 'Digital teknikk',         color: '#a78bfa' },
    arduino:      { label: 'Arduino og programmering', color: '#fb923c' },
  }
};

const QUESTIONS = [
  // ── Dataminne ──────────────────────────────────────────────────
  {
    cat: 'minne',
    q: 'Hva kjennetegner primærminne (RAM)?',
    opts: [
      'Flyktig minne som mister data uten strøm',
      'Permanent lagring',
      'Brukes som hovedminne under kjøring',
      'Basert på magnetplater',
    ],
    correct: 0,
    explain: 'RAM er flyktig – data forsvinner uten strøm. Det brukes som hovedminne under kjøring av programmer. Eksamen godkjenner også alternativ C; begge er riktige egenskaper.',
  },
  {
    cat: 'minne',
    q: 'Hva skiller DRAM fra SRAM?',
    opts: [
      'Må oppfriskes jevnlig',
      'SRAM er tregere enn DRAM',
      'DRAM er billigere å produsere',
      'SRAM brukes som cache',
    ],
    correct: 0,
    explain: 'DRAM må oppfriskes kontinuerlig fordi ladning lekker fra kondensatorene. Det gjør DRAM billigere men tregere enn SRAM. SRAM trenger ikke oppfriskning og brukes derfor som rask cache. Eksamen godkjenner A, C og D.',
  },
  {
    cat: 'minne',
    q: 'Hva lagres i ROM?',
    opts: [
      'Firmware/BIOS',
      'Prosessdata',
      'OS i drift',
      'Cache-data',
    ],
    correct: 0,
    explain: 'ROM (Read-Only Memory) lagrer firmware og BIOS – programvare som ikke endres under normal drift og som er tilgjengelig ved oppstart.',
  },
  {
    cat: 'minne',
    q: 'Hvilken ROM-type slettes med UV-lys?',
    opts: [
      'EEPROM',
      'Mask-ROM',
      'EPROM',
      'PROM',
    ],
    correct: 2,
    explain: 'EPROM (Erasable Programmable ROM) slettes ved å bestråle brikken med ultrafiolett (UV) lys gjennom et lite vindu i huset. EEPROM slettes elektronisk, PROM skrives én gang, og Mask-ROM programmeres under produksjon.',
  },
  {
    cat: 'minne',
    q: 'Hva kjennetegner EEPROM?',
    opts: [
      'Slettes elektronisk',
      'Kan kun skrives én gang',
      'Er flyktig',
      'Lagrer firmware',
    ],
    correct: 0,
    explain: 'EEPROM (Electrically Erasable Programmable ROM) kan slettes og skrives om elektronisk uten UV-lys. Det brukes ofte til firmware og innstillinger. Eksamen godkjenner A og D.',
  },
  {
    cat: 'minne',
    q: 'Hva skiller SSD fra HDD?',
    opts: [
      'Ingen bevegelige deler',
      'Tregere enn HDD',
      'Flash-lagring',
      'Mer robust mot støt og vibrasjon',
    ],
    correct: 0,
    explain: 'SSD har ingen bevegelige deler (bruker flash-minne), er raskere enn HDD, og mer robust mot mekaniske påvirkninger. Eksamen godkjenner A, C og D som korrekte egenskaper.',
  },
  {
    cat: 'minne',
    q: 'Hva er en ulempe med SSD?',
    opts: [
      'Begrenset antall skrive-/slettesykluser',
      'Treg tilgangstid',
      'Sårbar for vibrasjon',
      'Dyrere per GB enn HDD',
    ],
    correct: 0,
    explain: 'Flash-celler i en SSD tåler et begrenset antall skrive-/slettesykluser (typisk 3 000–100 000 P/E-sykluser avhengig av type). SSD er også dyrere per GB enn HDD. Eksamen godkjenner A og D.',
  },
  {
    cat: 'minne',
    q: 'Hva brukes cache til?',
    opts: [
      'Lagre ofte brukte data nær CPU',
      'Permanent lagring av filer',
      'Redusere ventetid ved dataaksess',
      'Øke lagringskapasiteten',
    ],
    correct: 0,
    explain: 'Cache-minne plasseres nær CPU og lagrer ofte brukte data og instruksjoner for å redusere ventetid. Eksamen godkjenner A og C – begge beskriver korrekte aspekter.',
  },
  {
    cat: 'minne',
    q: 'Hvor sitter L1-cache?',
    opts: [
      'I CPU-kjernen',
      'På hovedkortet, utenfor CPU',
      'Som en egen brikke på PCIe',
      'I RAM',
    ],
    correct: 0,
    explain: 'L1-cache er den raskeste og minste cachen, og er integrert direkte inne i CPU-kjernen. L2 og L3 kan sitte inne i CPU-pakken eller på hovedkortet avhengig av arkitektur.',
  },
  // ── Mikrokontroller ────────────────────────────────────────────
  {
    cat: 'mcu',
    q: 'Hva er en mikrokontroller?',
    opts: [
      'Kun et minnekort',
      'En liten datamaskin med CPU, minne og I/O',
      'En ren CPU uten minne',
      'En type sensor',
    ],
    correct: 1,
    explain: 'En mikrokontroller (MCU) er en komplett liten datamaskin på én enkelt brikke. Den inneholder CPU, RAM, Flash/ROM og I/O-porter for å styre eksterne enheter.',
  },
  {
    cat: 'mcu',
    q: 'Hva gjør en ADC?',
    opts: [
      'Omformer analog signal til digital signal',
      'Omformer digital signal til analog signal',
      'Komprimerer data',
      'Genererer klokkesignal',
    ],
    correct: 0,
    explain: 'ADC (Analog-to-Digital Converter) konverterer analoge spenningssignaler – for eksempel fra en temperatursensor – til digitale verdier som CPU-en kan behandle.',
  },
  {
    cat: 'analog',
    q: 'Hva brukes zenerdioder til?',
    opts: [
      'Likeretting av vekselspenning',
      'Spenningsstabilisering',
      'Signalforsterkning',
      'Transformasjon av spenning',
    ],
    correct: 1,
    explain: 'Zenerdioder holder en stabil spenning (zener-spenningen) over seg selv når de er i gjennombruddsmodus i sperreretning. Dette brukes til spenningsstabilisering og referansespenning.',
  },
  // ── Tallsystemer ───────────────────────────────────────────────
  {
    cat: 'tallsystemer',
    q: 'Konverter 1106₇ til desimal',
    opts: [
      '398₁₀',
      '101001110₂',
      '18E₁₆',
      '574₈',
    ],
    correct: 0,
    explain: '1106₇ = 1×7³ + 1×7² + 0×7 + 6 = 343 + 49 + 0 + 6 = 398₁₀. Merk at 18E₁₆ = 256+128+14 = 398₁₀ er også korrekt; eksamen godkjenner A og C.',
  },
  {
    cat: 'tallsystemer',
    q: 'Konverter 10101011₂ til desimal',
    opts: [
      '171₁₀',
      'AB₁₆',
      '253₁₀',
      'A9₁₆',
    ],
    correct: 0,
    explain: '10101011₂ = 128+32+8+2+1 = 171₁₀. I hex: 171 = 10×16+11 = AB₁₆. Eksamen godkjenner A (desimal) og B (hex).',
  },
  {
    cat: 'tallsystemer',
    q: 'Konverter AB₁₆ til desimal',
    opts: [
      '171₁₀',
      '10101011₂',
      '253₈',
      '1B₁₆',
    ],
    correct: 0,
    explain: 'AB₁₆ = 10×16 + 11 = 171₁₀. I binær: 171 = 10101011₂. I oktal: 171 = 2×64+5×8+3 = 253₈. Eksamen godkjenner A, B og C.',
  },
  {
    cat: 'tallsystemer',
    q: 'Konverter 1C4₁₆ til desimal',
    opts: [
      '452₁₀',
      '111000100₂',
      '704₈',
      '1B₁₆',
    ],
    correct: 0,
    explain: '1C4₁₆ = 1×256 + 12×16 + 4 = 256+192+4 = 452₁₀. I binær: 452 = 111000100₂. I oktal: 452 = 704₈. Eksamen godkjenner A, B og C.',
  },
  {
    cat: 'tallsystemer',
    q: 'Konverter 165₇ til desimal',
    opts: [
      '96₁₀',
      '60₁₆',
      '140₈',
      '1100000₂',
    ],
    correct: 0,
    explain: '165₇ = 1×49 + 6×7 + 5 = 49+42+5 = 96₁₀. Tilsvarende: 60₁₆ = 96₁₀, 140₈ = 96₁₀ og 1100000₂ = 96₁₀ – alle alternativene er korrekte.',
  },
  {
    cat: 'tallsystemer',
    q: 'Konverter 297₁₀ til binær',
    opts: [
      '100101001₂',
      '431₈',
      '129₁₆',
      '402₇',
    ],
    correct: 0,
    explain: '297₁₀ i binær: 256+32+8+1 = 100101001₂. I hex: 129₁₆ = 1×256+2×16+9 = 297₁₀. Eksamen godkjenner A og C.',
  },
  {
    cat: 'tallsystemer',
    q: 'Konverter 1E6₁₆ til desimal',
    opts: [
      '486₁₀',
      '111100110₂',
      '746₈',
      '196₁₅',
    ],
    correct: 0,
    explain: '1E6₁₆ = 1×256 + 14×16 + 6 = 256+224+6 = 486₁₀. I binær: 486 = 111100110₂. I oktal: 486 = 746₈. Eksamen godkjenner A, B og C.',
  },
  {
    cat: 'tallsystemer',
    q: 'Konverter 202₁₀ til base 5',
    opts: [
      '1302₅',
      '244₉',
      '174₁₁',
      'AC₁₉',
    ],
    correct: 0,
    explain: '202₁₀: 202÷5=40r2, 40÷5=8r0, 8÷5=1r3, 1÷5=0r1 → 1302₅. Alle fire alternativene er likeverdige konverteringer: 1302₅=244₉=174₁₁=AC₁₉=202₁₀. Eksamen godkjenner alle.',
  },
  // ── Mikrokontroller (avansert) ─────────────────────────────────
  {
    cat: 'mcu',
    q: 'Hva er den avgjørende forskjellen mellom en CPU og en mikrokontroller (MCU)?',
    opts: [
      'En MCU har alltid høyere klokkehastighet enn en CPU',
      'En CPU har innebygde I/O-porter',
      'En MCU er en komplett datamaskin på én brikke',
      'En MCU krever eksternt RAM for å fungere',
    ],
    correct: 2,
    explain: 'En MCU integrerer CPU, RAM, Flash og I/O-porter på én enkelt brikke – en komplett datamaskin. En vanlig CPU mangler disse periferikomponentene og trenger eksternt støtteutstyr.',
  },
  {
    cat: 'mcu',
    q: 'Hvorfor brukes NOR-flash oftere enn NAND-flash til firmware i mikrokontrollere?',
    opts: [
      'NOR-flash har lavere kapasitet',
      'NOR-flash tillater direkte kjøring (execute-in-place)',
      'NAND-flash er flyktig',
      'NOR-flash er raskere enn RAM',
    ],
    correct: 1,
    explain: 'NOR-flash gir rask tilfeldig leseaksess og støtter execute-in-place (XIP) – CPU-en kan lese og kjøre kode direkte fra flashen uten å kopiere til RAM. NAND-flash er optimalisert for sekvensiell lese/skriveaksess.',
  },
  {
    cat: 'mcu',
    q: 'Hvilken kombinasjon av egenskaper gjør SPI raskere enn I²C i praksis?',
    opts: [
      'SPI er asynkron og bruker færre ledninger',
      'SPI er synkron, full-duplex og har dedikerte datalinjer',
      'SPI har innebygd adressering',
      'SPI deler klokkelinje med andre busser',
    ],
    correct: 1,
    explain: 'SPI er synkront (felles klokkelinje), full-duplex (sender og mottar samtidig) og har dedikerte MOSI/MISO-linjer. Dette gir høyere gjennomstrømning enn I²C som er halvduplex og semisynkron.',
  },
  {
    cat: 'mcu',
    q: 'Hvorfor regnes UART som asynkron kommunikasjon?',
    opts: [
      'Den bruker ingen datalinjer',
      'Den mangler adressering',
      'Den bruker start- og stoppbiter i stedet for felles klokke',
      'Den kan ikke sende og motta samtidig',
    ],
    correct: 2,
    explain: 'UART har ingen felles klokkelinje mellom sender og mottaker. I stedet synkroniseres kommunikasjonen via startbit og stoppbit, og begge parter må ha avtalt samme baudrate.',
  },
  {
    cat: 'mcu',
    q: 'Hvilket utsagn beskriver RAM i en mikrokontroller mest korrekt?',
    opts: [
      'RAM lagrer programkode permanent',
      'RAM er flyktig og mister data ved strømbrudd',
      'RAM brukes kun til I/O-kommunikasjon',
      'RAM brukes til å lagre firmware',
    ],
    correct: 1,
    explain: 'RAM i en MCU er flyktig (volatile) – data forsvinner når strømmen slås av. Det brukes som arbeidsminne for variabler og stakk under programkjøring. Firmware lagres i Flash/ROM.',
  },
  {
    cat: 'mcu',
    q: 'Hvorfor er lavt strømforbruk avgjørende for MCU i IoT-applikasjoner?',
    opts: [
      'For å kunne bruke høyere klokkefrekvens',
      'For å redusere behovet for kjøling',
      'For å kunne drives lenge på batteri eller energi-høsting',
      'For å kunne bruke avanserte GPU-er',
    ],
    correct: 2,
    explain: 'IoT-enheter er ofte batteridrevne eller energi-høstende (solar, vibrasjon). Lavt strømforbruk – særlig i dvalemodus – er kritisk for lang batterilevetid uten hyppig vedlikehold.',
  },
  {
    cat: 'mcu',
    q: 'Hva er den viktigste årsaken til at timere er kritiske i mikrokontrollere?',
    opts: [
      'De brukes til lagring av data',
      'De muliggjør presis tidtaking, PWM og frekvensstyring',
      'De brukes til internettkommunikasjon',
      'De erstatter ADC og DAC',
    ],
    correct: 1,
    explain: 'Timere i MCU brukes til presis tidtaking, generering av PWM-signaler (f.eks. motorstyring), watchdog-funksjon og timing av kommunikasjonsprotokoller. De er uunnværlige i sanntidssystemer.',
  },
  {
    cat: 'mcu',
    q: 'Hvilken påstand om innebygde systemer er mest korrekt?',
    opts: [
      'De er optimalisert for generell databehandling',
      'De kjører alltid et fullt operativsystem',
      'De er utviklet for å utføre én eller få spesifikke oppgaver',
      'De krever store mengder RAM og grafikkytelse',
    ],
    correct: 2,
    explain: 'Innebygde systemer (embedded systems) er skreddersydd for én eller få definerte oppgaver. De er optimalisert for lav pris, lite strømforbruk og kompakt design – ikke generell databehandling.',
  },
  // ── Analog elektronikk ─────────────────────────────────────────
  {
    cat: 'analog',
    q: 'Hvilke likeretter-konfigurasjoner gir to strøm-topper per nettperiode?',
    opts: [
      'Helbølgelikeretter med senter-tapp',
      'Bro-likeretter',
      'Halvbølgelikeretter',
      'DC-kilde uten ripple',
    ],
    correct: 0,
    explain: 'Helbølgelikeretter med senter-tapp gir to topper per periode ved å utnytte begge halvperiodene. Bro-likeretteren (svar B) gjør det samme. Halvbølgelikeretter gir bare én topp per periode. Eksamen godkjenner A og B.',
  },
  {
    cat: 'analog',
    q: 'Velg passende seriemotstand for en zenerregulator: V_in = 8,5 V, V_z = 5,1 V, I_last = 10 mA, I_z_min = 3 mA. Formel: R = (V_in − V_z) / (I_last + I_z_min)',
    opts: [
      '≈ 262 Ω',
      '≈ 237 Ω',
      '≈ 290 Ω',
      '≈ 474 Ω',
    ],
    correct: 0,
    explain: 'R = (8,5 − 5,1) / (0,010 + 0,003) = 3,4 / 0,013 ≈ 261,5 Ω ≈ 262 Ω. Velg nærmeste standardverdi oppover (f.eks. 270 Ω) for å sikre minimum zenerstrøm.',
  },
  {
    cat: 'analog',
    q: 'Hva er ripple-frekvensen fra en halvbølgelikeretter ved 50 Hz nett?',
    opts: [
      '50 Hz',
      '100 Hz',
      '25 Hz',
      '200 Hz',
    ],
    correct: 0,
    explain: 'Halvbølgelikeretter benytter kun én halvperiode → ripple-frekvens = nettfrekvensen = 50 Hz. Helbølgelikeretter og bro-likeretter utnytter begge halvperioder og gir 100 Hz. Eksamen godkjenner A (50 Hz halvbølge), B (100 Hz helbølge/bro) og C (100 Hz bro).',
  },
  // ── Digital teknikk ────────────────────────────────────────────
  {
    cat: 'digital',
    q: 'Se figur. To NOR-porter koblede tilbake med Q og Q̄-utganger. Hva er denne kretsen?',
    opts: [
      'JK-vippe (flipflop)',
      'JK-vippe (latch)',
      'SR-vippe (latch)',
      'SR-vippe (flipflop)',
    ],
    correct: 3,
    explain: 'To krysskobledede NOR-porter danner en SR-krets. I pensum betegnes dette som SR-vippe (flipflop). SR har ugyldige tilstander (S=R=1) men ingen klokkeingang.',
  },
  {
    cat: 'digital',
    q: 'Se figur. En krets med klokkeingang (CLK), inverter og NAND-porter med Q og Q̄-utganger. Hva er dette?',
    opts: [
      'T-vippe (flipflop)',
      'JK-vippe (flipflop)',
      'D-vippe (flipflop)',
      'SR-vippe (flipflop)',
    ],
    correct: 2,
    explain: 'D-vippen (Data/Delay flip-flop) tar inn ett datasignal D og overfører det til utgangen Q ved klokkeflanken. Inverteren sørger for at D og D̄ alltid er inverse, og eliminerer den ugyldige tilstanden.',
  },
  {
    cat: 'digital',
    q: 'Hva er den forenklede formen til: F = A̅BC̅D + ABC̅D̅ + ABC̅D + BCD + ABCD + ABC?',
    opts: [
      'F = BC̅ + CD̅',
      'F = AC̅ + BCD̅ + AB',
      'F = AB + BD',
      'F = C̅D + A̅B',
    ],
    correct: 2,
    explain: 'ABC̅D̅ + ABC̅D = ABC̅. ABC̅ + ABC = AB. ABCD ⊂ ABC (allerede dekket). A̅BC̅D + BCD = BD(A̅+C). BD(A̅+C) + AB = AB + BD. Forenklet: F = AB + BD.',
  },
  {
    cat: 'digital',
    q: 'Hva er korrekt om T- og JK-vipper?',
    opts: [
      'T-vippe lages ved å sette J = K i en JK-vippe',
      'JK-vippe har en ugyldig tilstand (J=K=1)',
      'T-vippe bytter tilstand (toggle) ved T = 1',
      'JK kan fungere som T-vippe',
    ],
    correct: 0,
    explain: 'Ved J = K i en JK-vippe oppfører den seg som en T-vippe: J=K=0 holder tilstand, J=K=1 toggler. Eksamen godkjenner A, C og D som riktige påstander.',
  },
  {
    cat: 'digital',
    q: 'Hvilken påstand om tallsystemer er riktig?',
    opts: [
      '7F₁₆ = 127₁₀',
      '1255₁₀ = 4E7₁₆',
      '52 = 37₁₀',
      'Hex bruker 3 biter per siffer',
    ],
    correct: 0,
    explain: '7F₁₆ = 7×16 + 15 = 112 + 15 = 127₁₀ ✓. Hex bruker 4 biter per siffer (0–F). Svar C er ugyldig (5 er ikke et binært siffer).',
  },
  {
    cat: 'digital',
    q: 'Hvilke utsagn om F = A + B er riktige?',
    opts: [
      'Det er en OR-operasjon',
      'F = 0 kun når A = B = 0',
      'Tilsvarer brytere i serie',
      'Tilsvarer brytere i parallell',
    ],
    correct: 0,
    explain: 'F = A + B er OR: F = 0 kun når A = B = 0. Logisk tilsvarer det brytere i parallell (strøm kan gå gjennom enten A eller B). Eksamen godkjenner A, B og D.',
  },
  {
    cat: 'digital',
    q: 'Gitt F = A̅B̅ + AB̅ + A̅B + AB. Hva er F?',
    opts: [
      'F = 1 (alltid sann)',
      '4 enere i Karnaugh-diagrammet',
      'F = A + B',
      'Konstant høy',
    ],
    correct: 0,
    explain: 'F dekker alle fire mintermene (00, 01, 10, 11) for to variabler → F = 1 alltid. Karnaugh-diagrammet viser fire enere. Eksamen godkjenner A, B og D (A og D sier det samme).',
  },
  {
    cat: 'digital',
    q: 'Hvilke påstander gjelder for en asynkron MOD-5-teller?',
    opts: [
      'Krever 3 flip-flopper',
      'Resetter når telleverdien når 5',
      'Alle flip-flopper deler felles klokke',
      'Kan gi forsinkelsesfeil (ripple delay)',
    ],
    correct: 0,
    explain: 'MOD-5 krever ⌈log₂(5)⌉ = 3 flip-flopper. Telleren resetter ved 5 (0101₂). I asynkron (ripple) teller drives ikke alle FF av samme klokke – klokke propagerer fra FF til FF og gir forsinkelse. Eksamen godkjenner A, B og D.',
  },
  {
    cat: 'digital',
    q: 'Hvilke utsagn gjelder for en synkron MOD-5-nedteller?',
    opts: [
      'Alle flip-flopper deler felles klokke',
      'Sekvens: 4 → 3 → 2 → 1 → 0 → 4',
      'Neste tilstand beregnes parallelt for alle FF',
      'Er mer forsinket enn asynkron teller',
    ],
    correct: 0,
    explain: 'Synkron teller: felles klokke til alle FF (A), teller ned fra 4 til 0 og hopper tilbake til 4 (B), og neste tilstand beregnes kombinatorisk i parallell (C). Synkron er RASKERE enn asynkron – ikke mer forsinket. Eksamen godkjenner A, B og C.',
  },
  // ── ESD og EMC ─────────────────────────────────────────────────
  {
    cat: 'digital',
    q: 'Hvilke utsagn om ESD (elektrostatisk utladning) er riktige?',
    opts: [
      'ESD-hendelser kan være flere kV og svært raske (ns–µs)',
      'ESD vurderes i både kontakt- og luftutladning',
      'ESD påvirker kun mekaniske komponenter',
      'ESD kan forårsake latente skader som viser seg senere',
    ],
    correct: 0,
    explain: 'ESD-pulser er høyspenning (kV-nivå) og svært kortvarige (nanosekunder). De testes via kontaktutladning og luftutladning. ESD skader elektroniske kretser, ikke bare mekaniske deler, og kan gi latente skader. Eksamen godkjenner A, B og D.',
  },
  {
    cat: 'digital',
    q: 'Hva beskriver EMC (elektromagnetisk kompatibilitet) best?',
    opts: [
      'Evnen til å fungere tilfredsstillende i elektromagnetiske omgivelser og ikke forstyrre andre systemer',
      'Kun måling av strålt støy',
      'Både immunitet (robusthet mot støy) og utslipp',
      'Bare ESD-testing',
    ],
    correct: 0,
    explain: 'EMC handler om to sider: immunitet (tåle elektromagnetiske forstyrrelser fra omgivelsene) og utslipp (ikke forstyrre andre systemer). Eksamen godkjenner A og C.',
  },
  // ── Arduino og programmering ───────────────────────────────────
  {
    cat: 'arduino',
    q: 'Hvilke av følgende er eksempler på Arduino-kort?',
    opts: [
      'Arduino UNO',
      'Arduino Mega',
      'Raspberry Pi Pico',
      'Arduino Nano',
    ],
    correct: 0,
    explain: 'Arduino UNO, Mega og Nano er alle offisielle Arduino-kort. Raspberry Pi Pico er et eget produkt fra Raspberry Pi Foundation – ikke et Arduino-kort. Eksamen godkjenner A, B og D.',
  },
  {
    cat: 'arduino',
    q: 'Hva er hovedprogrammeringsspråket for Arduino?',
    opts: [
      'Python',
      'C++',
      'Java',
      'Arduinos eget språk (basert på C++)',
    ],
    correct: 3,
    explain: 'Arduino bruker et forenklet C++-basert språk med egne funksjoner som setup() og loop(). Det er i praksis C++ med Arduino-biblioteker. Eksamen godkjenner D (Arduinos eget språk basert på C++).',
  },
  {
    cat: 'arduino',
    q: 'Hvilke kommunikasjonsprotokoller støttes av de fleste Arduino-kort?',
    opts: [
      'SPI',
      'I2C',
      'USB-C',
      'UART',
    ],
    correct: 0,
    explain: 'De fleste Arduino-kort har innebygd SPI, I²C (Wire) og UART (Serial). USB-C er kun en kontaktorform, ikke en kommunikasjonsprotokoll i Arduino-kontekst. Eksamen godkjenner A, B og D.',
  },
  {
    cat: 'arduino',
    q: 'Hvilke av følgende er sensorer eller aktuatorer som brukes med mikrokontrollere?',
    opts: [
      'Temperaturføler',
      'Servomotor',
      'Ultrasonisk avstandsmåler',
      'Kondensator',
    ],
    correct: 0,
    explain: 'Temperaturføler er sensor (inndata), servomotor er aktuator (utdata), ultrasonisk avstandsmåler er sensor. Kondensator er en passiv komponent – verken sensor eller aktuator. Eksamen godkjenner A, B og C.',
  },
  {
    cat: 'arduino',
    q: 'Hva er formålet med en kontrollbuss?',
    opts: [
      'Transportere strøm til komponenter',
      'Styre overføringen mellom komponenter',
      'Øke datakapasiteten',
      'Inneholde operativsystemet',
    ],
    correct: 1,
    explain: 'Kontrollbussen bærer styresignaler som lese/skriv-kommandoer, avbrytssignaler og klokkesignaler. Den koordinerer kommunikasjonen mellom CPU, minne og I/O-enheter.',
  },
  {
    cat: 'arduino',
    q: 'Hva kjennetegner en parallell buss?',
    opts: [
      'Sender data ett bit av gangen',
      'Har separate ledere for hver bit',
      'Er tregere enn serielle busser',
      'Egner seg best for korte avstander',
    ],
    correct: 1,
    explain: 'Parallell buss overfører flere biter samtidig via separate ledere (f.eks. 8 eller 16 ledere for 8/16-bits data). Den egner seg best for korte avstander. Eksamen godkjenner B og D.',
  },
  {
    cat: 'arduino',
    q: 'Hva vil følgende Arduino-kode gjøre?\n\nsetup(): pinMode(13, OUTPUT)\nloop(): digitalWrite(13, HIGH) → delay(1000) → digitalWrite(13, LOW) → delay(1000)',
    opts: [
      'Blinke en LED på pin 13 med 1 sekunds intervall (1 sek på, 1 sek av)',
      'Slå på og av hele Arduino-kortet',
      'Skape en konstant høy spenning på pin 13',
      'Gi en tilfeldig blinkende effekt på pin 13',
    ],
    correct: 0,
    explain: 'Koden setter pin 13 som utgang, slår den PÅ (HIGH) i 1000 ms, slår den AV (LOW) i 1000 ms, og gjentar. Pin 13 har innebygd LED på de fleste Arduino-kort → klassisk blink-eksempel.',
  },
  {
    cat: 'arduino',
    q: 'Et program bruker DHT22-sensor og RTC (DS3231) for å overvåke temperatur. Hva gjør programmet?',
    opts: [
      'Logger maks/min-temperatur over ett døgn og slår på kortet',
      'Overskriver alltid maks- og min-temperatur ved hver måling',
      'Skriver tidspunktet når maks- og min-temperatur ble målt',
      'Bruker kun delay() og trenger ingen sanntidsklokke',
    ],
    correct: 2,
    explain: 'Programmet bruker RTC til å stemple tidspunktet for nye maks/min-målinger. Det oppdaterer bare maks/min når ny verdi faktisk er høyere/lavere enn gjeldende rekord, og skriver ut tidspunktet via Serial.',
  },
];
