'use strict';
const QUIZ_META = {
  id: 'trh1ek',
  title: 'TRH-1EK – Avsluttende prøve',
  subtitle: 'Quiz Elektroniske (Bjørns)',
  cats: {
    minne:        { label: 'Dataminne',               color: '#5c7cfa' },
    mcu:          { label: 'Mikrokontroller',          color: '#f59e0b' },
    tallsystemer: { label: 'Tallsystemer',             color: '#10b981' },
    analog:       { label: 'Analog elektronikk',       color: '#f472b6' },
    digital:      { label: 'Digital teknikk',          color: '#a78bfa' },
    arduino:      { label: 'Arduino og programmering', color: '#fb923c' },
  }
};

const QUESTIONS = [
  // ── Dataminne ──────────────────────────────────────────────────
  {
    cat: 'minne',
    q: 'Hva kjennetegner primærminne (RAM)?',
    opts: [
      'Flyktig minne som mister data uten strøm',
      'Permanent lagring',
      'Brukes som hovedminne under kjøring',
      'Basert på magnetplater',
    ],
    correct: [0, 2],
    explain: 'RAM er flyktig – data forsvinner uten strøm. Det brukes som hovedminne under kjøring av programmer. Permanent lagring er ROM/Flash, og magnetplater er HDD.',
  },
  {
    cat: 'minne',
    q: 'Hva skiller DRAM fra SRAM?',
    opts: [
      'DRAM må oppfriskes jevnlig',
      'SRAM er tregere enn DRAM',
      'DRAM er billigere å produsere',
      'SRAM brukes som cache',
    ],
    correct: [0, 2, 3],
    explain: 'DRAM bruker kondensatorer som lekker ladning og må oppfriskes kontinuerlig. Det gjør DRAM billigere men tregere enn SRAM. SRAM trenger ikke oppfriskning og brukes som rask cache.',
  },
  {
    cat: 'minne',
    q: 'Hva lagres i ROM?',
    opts: [
      'Firmware/BIOS',
      'Prosessdata',
      'OS i drift',
      'Cache-data',
    ],
    correct: 0,
    explain: 'ROM (Read-Only Memory) lagrer firmware og BIOS – programvare som ikke endres under normal drift og som er tilgjengelig ved oppstart.',
  },
  {
    cat: 'minne',
    q: 'Hvilken ROM-type slettes med UV-lys?',
    opts: [
      'EEPROM',
      'Mask-ROM',
      'EPROM',
      'PROM',
    ],
    correct: 2,
    explain: 'EPROM (Erasable Programmable ROM) slettes ved å bestråle brikken med ultrafiolett (UV) lys gjennom et lite vindu i huset. EEPROM slettes elektronisk, PROM skrives én gang, og Mask-ROM programmeres under produksjon.',
  },
  {
    cat: 'minne',
    q: 'Hva kjennetegner EEPROM?',
    opts: [
      'Slettes elektronisk',
      'Kan kun skrives én gang',
      'Er flyktig',
      'Lagrer firmware',
    ],
    correct: [0, 3],
    explain: 'EEPROM (Electrically Erasable Programmable ROM) kan slettes og skrives om elektronisk uten UV-lys. Det brukes ofte til firmware og konfigurasjon som må overleve strømbrudd.',
  },
  {
    cat: 'minne',
    q: 'Hva skiller SSD fra HDD?',
    opts: [
      'Ingen bevegelige deler',
      'Tregere enn HDD',
      'Flash-lagring',
      'Mer robust mot støt og vibrasjon',
    ],
    correct: [0, 2, 3],
    explain: 'SSD bruker flash-minne og har ingen bevegelige deler. Det gjør den raskere og mer robust mot mekanisk påvirkning enn en HDD med roterende plater.',
  },
  {
    cat: 'minne',
    q: 'Hva er ulemper med SSD?',
    opts: [
      'Begrenset antall skrive-/slettesykluser',
      'Treg tilgangstid',
      'Sårbar for vibrasjon',
      'Dyrere per GB enn HDD',
    ],
    correct: [0, 3],
    explain: 'Flash-celler tåler et begrenset antall P/E-sykluser (typisk 3 000–100 000 avhengig av type). SSD er også dyrere per GB enn HDD, selv om prisforskjellen krymper.',
  },
  {
    cat: 'minne',
    q: 'Hva brukes cache til?',
    opts: [
      'Lagre ofte brukte data nær CPU',
      'Permanent lagring av filer',
      'Redusere ventetid ved dataaksess',
      'Øke lagringskapasiteten',
    ],
    correct: [0, 2],
    explain: 'Cache-minne plasseres nær CPU og lagrer ofte brukte data og instruksjoner. Hensikten er å redusere ventetiden når CPU-en henter data fra det langsommere RAM-minnet.',
  },
  {
    cat: 'minne',
    q: 'Hvor sitter L1-cache?',
    opts: [
      'I CPU-kjernen',
      'På hovedkortet, utenfor CPU',
      'Som en egen brikke på PCIe',
      'I RAM',
    ],
    correct: 0,
    explain: 'L1-cache er den raskeste og minste cachen, og er integrert direkte inne i CPU-kjernen. L2 og L3 kan sitte inne i CPU-pakken eller på hovedkortet avhengig av arkitektur.',
  },
  // ── Mikrokontroller ────────────────────────────────────────────
  {
    cat: 'mcu',
    q: 'Hva er en mikrokontroller?',
    opts: [
      'Kun et minnekort',
      'En liten datamaskin med CPU, minne og I/O',
      'En ren CPU uten minne',
      'En type sensor',
    ],
    correct: 1,
    explain: 'En mikrokontroller (MCU) er en komplett liten datamaskin på én enkelt brikke. Den inneholder CPU, RAM, Flash/ROM og I/O-porter for å styre eksterne enheter.',
  },
  {
    cat: 'mcu',
    q: 'Hva gjør en ADC?',
    opts: [
      'Omformer analog signal til digital signal',
      'Omformer digital signal til analog signal',
      'Komprimerer data',
      'Genererer klokkesignal',
    ],
    correct: 0,
    explain: 'ADC (Analog-to-Digital Converter) konverterer analoge spenningssignaler – for eksempel fra en temperatursensor – til digitale verdier som CPU-en kan behandle.',
  },
  {
    cat: 'analog',
    q: 'Hva brukes zenerdioder til?',
    opts: [
      'Likeretting av vekselspenning',
      'Spenningsstabilisering',
      'Signalforsterkning',
      'Transformasjon av spenning',
    ],
    correct: 1,
    explain: 'Zenerdioder holder en stabil spenning (zener-spenningen) over seg selv i gjennombruddsmodus. Dette brukes til spenningsstabilisering og referansespenning i strømforsyninger.',
  },
  // ── Tallsystemer ───────────────────────────────────────────────
  {
    cat: 'tallsystemer',
    q: 'Konverter 1106₇ – hvilke av disse er korrekte svar?',
    opts: [
      '398₁₀',
      '100111110₂',
      '18E₁₆',
      '574₈',
    ],
    correct: [0, 2],
    explain: '1106₇ = 1×343 + 1×49 + 0×7 + 6 = 398₁₀. 18E₁₆ = 1×256 + 8×16 + 14 = 398₁₀ – samme verdi. 100111110₂ = 318 (feil), 574₈ = 380 (feil).',
  },
  {
    cat: 'tallsystemer',
    q: 'Konverter 10101011₂ – hvilke av disse er korrekte svar?',
    opts: [
      '171₁₀',
      'AB₁₆',
      '253₁₀',
      'A9₁₆',
    ],
    correct: [0, 1],
    explain: '10101011₂ = 128+32+8+2+1 = 171₁₀. 171 i hex: 171÷16=10r11 → AB₁₆. 253₁₀ og A9₁₆ (=169) er feil.',
  },
  {
    cat: 'tallsystemer',
    q: 'Konverter AB₁₆ – hvilke av disse er korrekte svar?',
    opts: [
      '171₁₀',
      '10101011₂',
      '253₈',
      '1B₁₆',
    ],
    correct: [0, 1, 2],
    explain: 'AB₁₆ = 10×16+11 = 171₁₀. 171 i binær = 10101011₂. 171 i oktal: 171÷8=21r3, 21÷8=2r5 → 253₈. 1B₁₆ = 27 (feil).',
  },
  {
    cat: 'tallsystemer',
    q: 'Konverter 1C4₁₆ – hvilke av disse er korrekte svar?',
    opts: [
      '452₁₀',
      '111000100₂',
      '704₈',
      '1B₁₆',
    ],
    correct: [0, 1, 2],
    explain: '1C4₁₆ = 1×256 + 12×16 + 4 = 452₁₀. 452 i binær = 111000100₂. 452 i oktal: 452÷8=56r4, 56÷8=7r0 → 704₈. 1B₁₆ = 27 (feil).',
  },
  {
    cat: 'tallsystemer',
    q: 'Konverter 165₇ – hvilke av disse er korrekte svar?',
    opts: [
      '96₁₀',
      '60₁₆',
      '140₈',
      '1100000₂',
    ],
    correct: [0, 1, 2, 3],
    explain: '165₇ = 1×49 + 6×7 + 5 = 96₁₀. 96 = 60₁₆ = 140₈ = 1100000₂ – alle fire alternativene er korrekte og likeverdige representasjoner av samme verdi.',
  },
  {
    cat: 'tallsystemer',
    q: 'Konverter 297₁₀ – hvilke av disse er korrekte svar?',
    opts: [
      '100101001₂',
      '431₈',
      '129₁₆',
      '402₇',
    ],
    correct: [0, 2],
    explain: '297 i binær: 256+32+8+1 = 100101001₂. 129₁₆ = 1×256+2×16+9 = 297₁₀ ✓. 431₈ = 4×64+3×8+1 = 281 (feil). 402₇ = 4×49+0+2 = 198 (feil).',
  },
  {
    cat: 'tallsystemer',
    q: 'Konverter 1E6₁₆ – hvilke av disse er korrekte svar?',
    opts: [
      '486₁₀',
      '111100110₂',
      '746₈',
      '196₁₅',
    ],
    correct: [0, 1, 2],
    explain: '1E6₁₆ = 1×256 + 14×16 + 6 = 486₁₀. 486 i binær = 111100110₂. 486 i oktal: 486÷8=60r6, 60÷8=7r4 → 746₈. 196₁₅ = 1×225+9×15+6 = 366 (feil).',
  },
  {
    cat: 'tallsystemer',
    q: 'Konverter 202₁₀ – hvilke av disse er korrekte svar?',
    opts: [
      '1302₅',
      '244₉',
      '174₁₁',
      'AC₁₉',
    ],
    correct: [0, 1, 2, 3],
    explain: '202₁₀: 1302₅ (1×125+3×25+2=202 ✓), 244₉ (2×81+4×9+4=202 ✓), 174₁₁ (1×121+7×11+4=202 ✓), AC₁₉ (10×19+12=202 ✓). Alle fire er korrekte.',
  },
  // ── Mikrokontroller (avansert) ─────────────────────────────────
  {
    cat: 'mcu',
    q: 'Hva er den avgjørende forskjellen mellom en CPU og en mikrokontroller (MCU)?',
    opts: [
      'En MCU har alltid høyere klokkehastighet enn en CPU',
      'En CPU har innebygde I/O-porter',
      'En MCU er en komplett datamaskin på én brikke',
      'En MCU krever eksternt RAM for å fungere',
    ],
    correct: 2,
    explain: 'En MCU integrerer CPU, RAM, Flash og I/O-porter på én enkelt brikke – en komplett datamaskin. En vanlig CPU mangler disse periferikomponentene og trenger eksternt støtteutstyr.',
  },
  {
    cat: 'mcu',
    q: 'Hvorfor brukes NOR-flash oftere enn NAND-flash til firmware i mikrokontrollere?',
    opts: [
      'NOR-flash har lavere kapasitet',
      'NOR-flash tillater direkte kjøring (execute-in-place)',
      'NAND-flash er flyktig',
      'NOR-flash er raskere enn RAM',
    ],
    correct: 1,
    explain: 'NOR-flash gir rask tilfeldig leseaksess og støtter execute-in-place (XIP) – CPU-en kan kjøre kode direkte fra flashen uten å kopiere til RAM. NAND er optimalisert for sekvensiell lese/skriveaksess.',
  },
  {
    cat: 'mcu',
    q: 'Hvilken kombinasjon av egenskaper gjør SPI raskere enn I²C i praksis?',
    opts: [
      'SPI er asynkron og bruker færre ledninger',
      'SPI er synkron, full-duplex og har dedikerte datalinjer',
      'SPI har innebygd adressering',
      'SPI deler klokkelinje med andre busser',
    ],
    correct: 1,
    explain: 'SPI er synkront (felles klokkelinje), full-duplex (sender og mottar samtidig) og har dedikerte MOSI/MISO-linjer. Dette gir høyere gjennomstrømning enn I²C som er halvduplex.',
  },
  {
    cat: 'mcu',
    q: 'Hvorfor regnes UART som asynkron kommunikasjon?',
    opts: [
      'Den bruker ingen datalinjer',
      'Den mangler adressering',
      'Den bruker start- og stoppbiter i stedet for felles klokke',
      'Den kan ikke sende og motta samtidig',
    ],
    correct: 2,
    explain: 'UART har ingen felles klokkelinje. I stedet synkroniseres kommunikasjonen via startbit og stoppbit, og begge parter må ha avtalt samme baudrate på forhånd.',
  },
  {
    cat: 'mcu',
    q: 'Hvilket utsagn beskriver RAM i en mikrokontroller mest korrekt?',
    opts: [
      'RAM lagrer programkode permanent',
      'RAM er flyktig og mister data ved strømbrudd',
      'RAM brukes kun til I/O-kommunikasjon',
      'RAM brukes til å lagre firmware',
    ],
    correct: 1,
    explain: 'RAM i en MCU er flyktig – data forsvinner når strømmen slås av. Det brukes som arbeidsminne for variabler og stakk under programkjøring. Firmware lagres i Flash/ROM.',
  },
  {
    cat: 'mcu',
    q: 'Hvorfor er lavt strømforbruk avgjørende for MCU i IoT-applikasjoner?',
    opts: [
      'For å kunne bruke høyere klokkefrekvens',
      'For å redusere behovet for kjøling',
      'For å kunne drives lenge på batteri eller energi-høsting',
      'For å kunne bruke avanserte GPU-er',
    ],
    correct: 2,
    explain: 'IoT-enheter er ofte batteridrevne eller energi-høstende (solar, vibrasjon). Lavt strømforbruk – særlig i dvalemodus – er kritisk for lang batterilevetid uten hyppig vedlikehold.',
  },
  {
    cat: 'mcu',
    q: 'Hva er den viktigste årsaken til at timere er kritiske i mikrokontrollere?',
    opts: [
      'De brukes til lagring av data',
      'De muliggjør presis tidtaking, PWM og frekvensstyring',
      'De brukes til internettkommunikasjon',
      'De erstatter ADC og DAC',
    ],
    correct: 1,
    explain: 'Timere i MCU brukes til presis tidtaking, generering av PWM-signaler (f.eks. motorstyring), watchdog-funksjon og timing av kommunikasjonsprotokoller.',
  },
  {
    cat: 'mcu',
    q: 'Hvilken påstand om innebygde systemer er mest korrekt?',
    opts: [
      'De er optimalisert for generell databehandling',
      'De kjører alltid et fullt operativsystem',
      'De er utviklet for å utføre én eller få spesifikke oppgaver',
      'De krever store mengder RAM og grafikkytelse',
    ],
    correct: 2,
    explain: 'Innebygde systemer (embedded systems) er skreddersydd for én eller få definerte oppgaver. De er optimalisert for lav pris, lite strømforbruk og kompakt design.',
  },
  // ── Analog elektronikk ─────────────────────────────────────────
  {
    cat: 'analog',
    q: 'Hvilke konfigurasjoner gir to strøm-topper per nettperiode?',
    opts: [
      'Helbølgelikeretter med senter-tapp',
      'Bro-likeretter',
      'Halvbølgelikeretter',
      'DC-kilde uten ripple',
    ],
    correct: [0, 1],
    explain: 'Helbølgelikeretter med senter-tapp og bro-likeretter utnytter begge halvperiodene og gir to strøm-topper per nettperiode (ripple-frekvens 100 Hz ved 50 Hz nett). Halvbølgelikeretter gir bare én topp.',
  },
  {
    cat: 'analog',
    q: 'Velg passende seriemotstand for en zenerregulator:\nV<sub>in</sub> = 8,5 V, V<sub>z</sub> = 5,1 V, I<sub>last</sub> = 10 mA, I<sub>z,min</sub> = 3 mA\nR = (V<sub>in</sub> − V<sub>z</sub>) / (I<sub>last</sub> + I<sub>z,min</sub>)',
    opts: [
      '≈ 262 Ω',
      '≈ 237 Ω',
      '≈ 290 Ω',
      '≈ 474 Ω',
    ],
    correct: 0,
    explain: 'R = (8,5 − 5,1) / (0,010 + 0,003) = 3,4 / 0,013 ≈ 261,5 Ω ≈ 262 Ω. Velg nærmeste standardverdi oppover (f.eks. 270 Ω) for å sikre minimum zenerstrøm.',
  },
  {
    cat: 'analog',
    q: 'Hva er typiske ripple-frekvenser fra ulike likerettertyper ved 50 Hz nett?',
    opts: [
      'Halvbølgelikeretter: 50 Hz',
      'Helbølgelikeretter med senter-tapp: 100 Hz',
      'Bro-likeretter: 100 Hz',
      'Bro-likeretter: 50 Hz',
    ],
    correct: [0, 1, 2],
    explain: 'Halvbølge utnytter én halvperiode → 50 Hz ripple. Helbølge (senter-tapp) og bro-likeretter utnytter begge halvperiodene → 100 Hz ripple. Bro-likeretter gir ikke 50 Hz.',
  },
  // ── Digital teknikk ────────────────────────────────────────────
  {
    cat: 'digital',
    q: 'Se figur: to krysskoblede NOR-porter med Q og Q̄-utganger. Hva er kretsen?',
    img: '<img src="sr-nor-krets.svg" style="max-width:100%;border-radius:8px;display:block;margin:0 auto 8px;">',
    opts: [
      'JK-vippe (flipflop)',
      'JK-vippe (latch)',
      'SR-vippe (latch)',
      'SR-vippe (flipflop)',
    ],
    correct: 2,
    explain: 'To krysskoblede NOR-porter danner en SR-latch. En latch har ingen klokkeingang og reagerer direkte på inngangsnivå – det er nettopp det som skiller den fra en flipflop. SR-latchen har ugyldig tilstand ved S=R=1.',
  },
  {
    cat: 'digital',
    q: 'Se figur: krets med klokkeingang, inverterer og NAND-porter med Q og Q̄. Hva er dette?',
    img: '<img src="d-nand-krets.svg" style="max-width:100%;border-radius:8px;display:block;margin:0 auto 8px;">',
    opts: [
      'T-vippe (flipflop)',
      'JK-vippe (flipflop)',
      'D-vippe (flipflop)',
      'SR-vippe (flipflop)',
    ],
    correct: 2,
    explain: 'D-vippen (Data/Delay) tar inn ett datasignal D og overfører det til Q ved klokkeflanken. Inverteren sørger for at D og D̄ alltid er inverse og eliminerer ugyldig tilstand.',
  },
  {
    cat: 'digital',
    q: 'Hva er den forenklede formen til F = A̅BC̅D + ABC̅D̅ + ABC̅D + BCD + ABCD + ABC?',
    opts: [
      'F = BC̅ + CD̅',
      'F = AC̅ + BCD̅ + AB',
      'F = AB + BD',
      'F = C̅D + A̅B',
    ],
    correct: 2,
    explain: 'ABC̅D̅ + ABC̅D = ABC̅. ABC̅ + ABC = AB. A̅BC̅D + BCD = BD(A̅+C). AB + BD(A̅+C) = AB + A̅BD + BCD = AB + BD. Forenklet: F = AB + BD.',
  },
  {
    cat: 'digital',
    q: 'Hva er korrekt om T- og JK-vipper?',
    opts: [
      'T-vippe lages ved å sette J = K i en JK-vippe',
      'JK-vippe har ugyldig tilstand ved J=K=1',
      'T-vippe bytter tilstand (toggle) ved T = 1',
      'JK kan fungere som T-vippe',
    ],
    correct: [0, 2, 3],
    explain: 'Ved J=K i en JK-vippe oppfører den seg som en T-vippe (toggle). J=K=0 holder tilstand, J=K=1 toggler. JK har ikke ugyldig tilstand – det er SR-vippen som har det (S=R=1 er ugyldig).',
  },
  {
    cat: 'digital',
    q: 'Hvilke påstander om tallsystemer er riktige?',
    opts: [
      '7F₁₆ = 127₁₀',
      '1255₁₀ = 4E7₁₆',
      '5₂ = 37₁₀',
      'Hex bruker 3 biter per siffer',
    ],
    correct: [0, 1],
    explain: '7F₁₆ = 7×16 + 15 = 127₁₀ ✓. 4E7₁₆ = 4×256 + 14×16 + 7 = 1255₁₀ ✓. 5₂ er ugyldig – 5 er ikke et lovlig binært siffer. Hex bruker 4 biter per siffer (nibble).',
  },
  {
    cat: 'digital',
    q: 'Hvilke utsagn om F = A + B er riktige?',
    opts: [
      'Det er en OR-operasjon',
      'F = 0 kun når A = B = 0',
      'Tilsvarer brytere i serie',
      'Tilsvarer brytere i parallell',
    ],
    correct: [0, 1, 3],
    explain: 'F = A + B er OR: F = 0 bare når begge inngangene er 0. Kretsmessig tilsvarer det to brytere i parallell – strøm kan gå gjennom enten A eller B. Brytere i serie er AND-operasjon.',
  },
  {
    cat: 'digital',
    q: 'Gitt F = A̅B̅ + AB̅ + A̅B + AB. Hvilke påstander stemmer?',
    opts: [
      'F = 1 (alltid sann)',
      '4 enere i Karnaugh-diagrammet',
      'F = A + B',
      'Konstant høy',
    ],
    correct: [0, 1, 3],
    explain: 'F dekker alle fire mintermene for to variabler → F = 1 alltid (konstant høy). Karnaugh-diagrammet viser fire enere. F = A + B er feil fordi A+B = 0 når A=B=0, mens F alltid er 1.',
  },
  {
    cat: 'digital',
    q: 'Hvilke påstander gjelder for en asynkron MOD-5-teller?',
    opts: [
      'Krever 3 flip-flopper',
      'Resetter når telleverdien når 5',
      'Alle flip-flopper deler felles klokke',
      'Kan gi forsinkelsesfeil (ripple delay)',
    ],
    correct: [0, 1, 3],
    explain: 'MOD-5 krever ⌈log₂(5)⌉ = 3 flip-flopper. Telleren resetter ved 5 (0101₂). I asynkron (ripple) teller propagerer klokken fra FF til FF – ingen felles klokke, og forsinkelse er en kjent svakhet.',
  },
  {
    cat: 'digital',
    q: 'Hvilke utsagn gjelder for en synkron MOD-5-nedteller?',
    opts: [
      'Alle flip-flopper deler felles klokke',
      'Sekvens: 4 → 3 → 2 → 1 → 0 → 4',
      'Neste tilstand beregnes parallelt for alle FF',
      'Er mer forsinket enn asynkron teller',
    ],
    correct: [0, 1, 2],
    explain: 'Synkron teller: felles klokke til alle FF, teller ned 4→3→2→1→0→4, og neste tilstand beregnes kombinatorisk i parallell. Synkron er RASKERE enn asynkron – ikke mer forsinket.',
  },
  // ── ESD og EMC ─────────────────────────────────────────────────
  {
    cat: 'digital',
    q: 'Hvilke utsagn om ESD (elektrostatisk utladning) er riktige?',
    opts: [
      'ESD-hendelser kan være flere kV og svært raske (ns–µs)',
      'ESD vurderes i både kontakt- og luftutladning',
      'ESD påvirker kun mekaniske komponenter',
      'ESD kan forårsake latente skader som viser seg senere',
    ],
    correct: [0, 1, 3],
    explain: 'ESD-pulser er høyspenning (kV-nivå) og svært kortvarige. De testes via kontaktutladning og luftutladning. ESD skader elektroniske kretser – ikke bare mekaniske deler – og kan gi latente skader.',
  },
  {
    cat: 'digital',
    q: 'Hva beskriver EMC (elektromagnetisk kompatibilitet) best?',
    opts: [
      'Evnen til å fungere tilfredsstillende i elektromagnetiske omgivelser og ikke forstyrre andre systemer',
      'Kun måling av strålt støy',
      'Både immunitet (robusthet mot støy) og utslipp',
      'Bare ESD-testing',
    ],
    correct: [0, 2],
    explain: 'EMC handler om to sider: immunitet (tåle forstyrrelser) og utslipp (ikke forstyrre andre). Begge alternativene A og C beskriver dette korrekt fra ulike vinkler.',
  },
  // ── Arduino og programmering ───────────────────────────────────
  {
    cat: 'arduino',
    q: 'Hvilke av følgende er eksempler på Arduino-kort?',
    opts: [
      'Arduino UNO',
      'Arduino Mega',
      'Raspberry Pi Pico',
      'Arduino Nano',
    ],
    correct: [0, 1, 3],
    explain: 'Arduino UNO, Mega og Nano er alle offisielle Arduino-kort. Raspberry Pi Pico er et eget produkt fra Raspberry Pi Foundation og ikke et Arduino-kort.',
  },
  {
    cat: 'arduino',
    q: 'Hva er hovedprogrammeringsspråket for Arduino?',
    opts: [
      'Python',
      'C++',
      'Java',
      'Arduinos eget språk (basert på C++)',
    ],
    correct: 3,
    explain: 'Arduino bruker et forenklet C++-basert språk med egne funksjoner som setup() og loop(). Det er i praksis C++ med Arduino-biblioteker, men presenteres som Arduinos eget språk.',
  },
  {
    cat: 'arduino',
    q: 'Hvilke kommunikasjonsprotokoller støttes av de fleste Arduino-kort?',
    opts: [
      'SPI',
      'I2C',
      'USB-C',
      'UART',
    ],
    correct: [0, 1, 3],
    explain: 'De fleste Arduino-kort har innebygd SPI, I²C (Wire-biblioteket) og UART (Serial). USB-C er en kontaktorform, ikke en kommunikasjonsprotokoll i Arduino-kontekst.',
  },
  {
    cat: 'arduino',
    q: 'Hvilke av følgende er sensorer eller aktuatorer som brukes med mikrokontrollere?',
    opts: [
      'Temperaturføler',
      'Servomotor',
      'Ultrasonisk avstandsmåler',
      'Kondensator',
    ],
    correct: [0, 1, 2],
    explain: 'Temperaturføler og ultrasonisk avstandsmåler er sensorer (inndata). Servomotor er en aktuator (utdata). Kondensator er en passiv komponent – verken sensor eller aktuator.',
  },
  {
    cat: 'arduino',
    q: 'Hva er formålet med en kontrollbuss?',
    opts: [
      'Transportere strøm til komponenter',
      'Styre overføringen mellom komponenter',
      'Øke datakapasiteten',
      'Inneholde operativsystemet',
    ],
    correct: 1,
    explain: 'Kontrollbussen bærer styresignaler som lese/skriv-kommandoer, avbrytssignaler og klokkesignaler. Den koordinerer kommunikasjonen mellom CPU, minne og I/O-enheter.',
  },
  {
    cat: 'arduino',
    q: 'Hva kjennetegner en parallell buss?',
    opts: [
      'Sender data ett bit av gangen',
      'Har separate ledere for hver bit',
      'Er tregere enn serielle busser',
      'Egner seg best for korte avstander',
    ],
    correct: [1, 3],
    explain: 'Parallell buss overfører flere biter samtidig via separate ledere. Den er raskere enn serielle busser men egner seg best for korte avstander (krosstalk øker med lengde). Én bit av gangen er kjennetegn på seriell buss.',
  },
  {
    cat: 'arduino',
    q: 'Hva vil følgende Arduino-kode gjøre?<br><code class="code-block">void setup() {\n  pinMode(13, OUTPUT);\n}\n\nvoid loop() {\n  digitalWrite(13, HIGH);\n  delay(1000);\n  digitalWrite(13, LOW);\n  delay(1000);\n}</code>',
    opts: [
      'Blinke en LED på pin 13 med 1 sekunds intervall (1 sek på, 1 sek av)',
      'Slå på og av hele Arduino-kortet',
      'Skape en konstant høy spenning på pin 13',
      'Gi en tilfeldig blinkende effekt på pin 13',
    ],
    correct: 0,
    explain: 'Koden setter pin 13 som utgang, slår den PÅ (HIGH) i 1000 ms, slår den AV (LOW) i 1000 ms, og gjentar. Pin 13 har innebygd LED på de fleste Arduino-kort – klassisk blink-eksempel.',
  },
  {
    cat: 'arduino',
    q: 'Hva gjør følgende Arduino-program?<br><code class="code-block">#include &lt;RTClib.h&gt;\n#include &lt;Wire.h&gt;\n#include &lt;DHT.h&gt;\n\n#define DHTPIN 2\n#define DHTTYPE DHT22\n\nDHT dht(DHTPIN, DHTTYPE);\nRTC_DS3231 rtc;\n\nfloat maxTemp = -1000;\nfloat minTemp = 1000;\nDateTime timeMax;\nDateTime timeMin;\n\nvoid setup() {\n  Serial.begin(9600);\n  dht.begin();\n  rtc.begin();\n}\n\nvoid loop() {\n  float currentTemp = dht.readTemperature();\n  DateTime now = rtc.now();\n\n  if (isnan(currentTemp)) {\n    Serial.println("Feil ved lesing av temperatur");\n    return;\n  }\n  if (currentTemp &gt; maxTemp) {\n    maxTemp = currentTemp;\n    timeMax = now;\n  }\n  if (currentTemp &lt; minTemp) {\n    minTemp = currentTemp;\n    timeMin = now;\n  }\n  Serial.print("Temp: ");  Serial.print(currentTemp);\n  Serial.print(" | Max: "); Serial.print(maxTemp);\n  Serial.print(" (");      Serial.print(timeMax.timestamp()); Serial.print(")");\n  Serial.print(" | Min: "); Serial.print(minTemp);\n  Serial.print(" (");      Serial.println(timeMin.timestamp()); Serial.println(")");\n  delay(60000);\n}</code>',
    opts: [
      'Programmet bruker DHT22 og RTC for å logge maks/min-temperatur, og skriver tidspunkt for når de ble målt',
      'Programmet overskriver alltid både maks- og min-temperatur ved hver måling',
      'Programmet skriver tidspunktet når maks- og min-temperatur ble målt',
      'Programmet bruker kun delay() og trenger ingen sanntidsklokke',
    ],
    correct: 2,
    explain: 'Programmet oppdaterer maxTemp/minTemp kun når ny verdi er høyere/lavere enn gjeldende rekord, og lagrer tidspunktet (RTC) for når rekorden ble satt. Resultatet skrives løpende via Serial.',
  },
];
